$ Spice netlist generated by v2lvs
$ v2020.1_25.14    Mon Feb 3 16:40:08 PST 2020
*.BUSDELIMITER [ 

.SUBCKT datapath__0_24 M_greatest[23] M_greatest[22] M_greatest[21] 
+ M_greatest[20] M_greatest[19] M_greatest[18] M_greatest[17] M_greatest[16] 
+ M_greatest[15] M_greatest[14] M_greatest[13] M_greatest[12] M_greatest[11] 
+ M_greatest[10] M_greatest[9] M_greatest[8] M_greatest[7] M_greatest[6] 
+ M_greatest[5] M_greatest[4] M_greatest[3] M_greatest[2] M_greatest[1] 
+ M_greatest[0] p_0[31] p_0[30] p_0[29] p_0[28] p_0[27] p_0[26] p_0[25] p_0[24] 
+ p_0[23] p_0[22] p_0[21] p_0[20] p_0[19] p_0[18] p_0[17] p_0[16] p_0[15] 
+ p_0[14] p_0[13] p_0[12] p_0[11] p_0[10] p_0[9] p_0[8] p_0[7] p_0[6] p_0[5] 
+ p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] 
Xi_46 INV_X1 $PINS ZN=n_23 A=M_greatest[19] 
Xi_45 INV_X1 $PINS ZN=n_22 A=M_greatest[15] 
Xi_44 INV_X1 $PINS ZN=n_21 A=M_greatest[11] 
Xi_43 OR3_X1 $PINS ZN=n_20 A1=M_greatest[2] A2=M_greatest[1] A3=M_greatest[0] 
Xi_42 OR2_X1 $PINS ZN=n_19 A1=n_20 A2=M_greatest[3] 
Xi_41 OR2_X1 $PINS ZN=n_18 A1=n_19 A2=M_greatest[4] 
Xi_40 OR3_X1 $PINS ZN=n_17 A1=n_18 A2=M_greatest[5] A3=M_greatest[6] 
Xi_39 OR2_X1 $PINS ZN=n_16 A1=n_17 A2=M_greatest[7] 
Xi_38 OR3_X1 $PINS ZN=n_15 A1=n_16 A2=M_greatest[8] A3=M_greatest[9] 
Xi_37 NOR2_X1 $PINS ZN=n_14 A1=n_15 A2=M_greatest[10] 
Xi_36 NAND2_X1 $PINS ZN=n_13 A1=n_14 A2=n_21 
Xi_35 OR2_X1 $PINS ZN=n_12 A1=n_13 A2=M_greatest[12] 
Xi_34 NOR2_X1 $PINS ZN=n_11 A1=n_12 A2=M_greatest[13] 
Xi_33 NOR3_X1 $PINS ZN=n_10 A1=n_12 A2=M_greatest[13] A3=M_greatest[14] 
Xi_32 NAND2_X1 $PINS ZN=n_9 A1=n_10 A2=n_22 
Xi_31 OR2_X1 $PINS ZN=n_8 A1=n_9 A2=M_greatest[16] 
Xi_30 NOR2_X1 $PINS ZN=n_7 A1=n_8 A2=M_greatest[17] 
Xi_29 NOR3_X1 $PINS ZN=n_6 A1=n_8 A2=M_greatest[17] A3=M_greatest[18] 
Xi_28 NAND2_X1 $PINS ZN=n_5 A1=n_6 A2=n_23 
Xi_27 OR2_X1 $PINS ZN=n_4 A1=n_5 A2=M_greatest[20] 
Xi_26 NOR2_X1 $PINS ZN=n_3 A1=n_4 A2=M_greatest[21] 
Xi_25 NOR3_X1 $PINS ZN=p_0[23] A1=n_4 A2=M_greatest[21] A3=M_greatest[22] 
Xi_24 XNOR2_X1 $PINS ZN=p_0[22] A=M_greatest[22] B=n_3 
Xi_23 XOR2_X1 $PINS Z=p_0[21] A=M_greatest[21] B=n_4 
Xi_22 XOR2_X1 $PINS Z=p_0[20] A=M_greatest[20] B=n_5 
Xi_21 XNOR2_X1 $PINS ZN=p_0[19] A=M_greatest[19] B=n_6 
Xi_20 XNOR2_X1 $PINS ZN=p_0[18] A=M_greatest[18] B=n_7 
Xi_19 XOR2_X1 $PINS Z=p_0[17] A=M_greatest[17] B=n_8 
Xi_18 XOR2_X1 $PINS Z=p_0[16] A=M_greatest[16] B=n_9 
Xi_17 XNOR2_X1 $PINS ZN=p_0[15] A=M_greatest[15] B=n_10 
Xi_16 XNOR2_X1 $PINS ZN=p_0[14] A=M_greatest[14] B=n_11 
Xi_15 XOR2_X1 $PINS Z=p_0[13] A=M_greatest[13] B=n_12 
Xi_14 XOR2_X1 $PINS Z=p_0[12] A=M_greatest[12] B=n_13 
Xi_13 XNOR2_X1 $PINS ZN=p_0[11] A=M_greatest[11] B=n_14 
Xi_12 XOR2_X1 $PINS Z=p_0[10] A=M_greatest[10] B=n_15 
Xi_11 OAI21_X1 $PINS ZN=n_2 A=M_greatest[9] B1=n_16 B2=M_greatest[8] 
Xi_10 AND2_X1 $PINS ZN=p_0[9] A1=n_15 A2=n_2 
Xi_9 XOR2_X1 $PINS Z=p_0[8] A=M_greatest[8] B=n_16 
Xi_8 XOR2_X1 $PINS Z=p_0[7] A=M_greatest[7] B=n_17 
Xi_7 OAI21_X1 $PINS ZN=n_1 A=M_greatest[6] B1=n_18 B2=M_greatest[5] 
Xi_6 AND2_X1 $PINS ZN=p_0[6] A1=n_17 A2=n_1 
Xi_5 XOR2_X1 $PINS Z=p_0[5] A=M_greatest[5] B=n_18 
Xi_4 XOR2_X1 $PINS Z=p_0[4] A=M_greatest[4] B=n_19 
Xi_3 XOR2_X1 $PINS Z=p_0[3] A=M_greatest[3] B=n_20 
Xi_2 OAI21_X1 $PINS ZN=n_0 A=M_greatest[2] B1=M_greatest[1] B2=M_greatest[0] 
Xi_1 AND2_X1 $PINS ZN=p_0[2] A1=n_20 A2=n_0 
Xi_0 XOR2_X1 $PINS Z=p_0[1] A=M_greatest[1] B=M_greatest[0] 
.ENDS

.SUBCKT datapath__0_21 M_shitfed[23] M_shitfed[22] M_shitfed[21] M_shitfed[20] 
+ M_shitfed[19] M_shitfed[18] M_shitfed[17] M_shitfed[16] M_shitfed[15] 
+ M_shitfed[14] M_shitfed[13] M_shitfed[12] M_shitfed[11] M_shitfed[10] 
+ M_shitfed[9] M_shitfed[8] M_shitfed[7] M_shitfed[6] M_shitfed[5] M_shitfed[4] 
+ M_shitfed[3] M_shitfed[2] M_shitfed[1] M_shitfed[0] p_0[31] p_0[30] p_0[29] 
+ p_0[28] p_0[27] p_0[26] p_0[25] p_0[24] p_0[23] p_0[22] p_0[21] p_0[20] 
+ p_0[19] p_0[18] p_0[17] p_0[16] p_0[15] p_0[14] p_0[13] p_0[12] p_0[11] 
+ p_0[10] p_0[9] p_0[8] p_0[7] p_0[6] p_0[5] p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] 
Xi_47 INV_X1 $PINS ZN=n_23 A=M_shitfed[15] 
Xi_46 INV_X1 $PINS ZN=n_22 A=M_shitfed[11] 
Xi_45 OR3_X1 $PINS ZN=n_21 A1=M_shitfed[2] A2=M_shitfed[1] A3=M_shitfed[0] 
Xi_44 OR2_X1 $PINS ZN=n_20 A1=n_21 A2=M_shitfed[3] 
Xi_43 OR2_X1 $PINS ZN=n_19 A1=n_20 A2=M_shitfed[4] 
Xi_42 OR3_X1 $PINS ZN=n_18 A1=n_19 A2=M_shitfed[5] A3=M_shitfed[6] 
Xi_41 OR2_X1 $PINS ZN=n_17 A1=n_18 A2=M_shitfed[7] 
Xi_40 OR3_X1 $PINS ZN=n_16 A1=n_17 A2=M_shitfed[8] A3=M_shitfed[9] 
Xi_39 NOR2_X1 $PINS ZN=n_15 A1=n_16 A2=M_shitfed[10] 
Xi_38 NAND2_X1 $PINS ZN=n_14 A1=n_15 A2=n_22 
Xi_37 OR2_X1 $PINS ZN=n_13 A1=n_14 A2=M_shitfed[12] 
Xi_36 NOR2_X1 $PINS ZN=n_12 A1=n_13 A2=M_shitfed[13] 
Xi_35 NOR3_X1 $PINS ZN=n_11 A1=n_13 A2=M_shitfed[13] A3=M_shitfed[14] 
Xi_34 NAND2_X1 $PINS ZN=n_10 A1=n_11 A2=n_23 
Xi_33 OR2_X1 $PINS ZN=n_9 A1=n_10 A2=M_shitfed[16] 
Xi_32 OR2_X1 $PINS ZN=n_8 A1=n_9 A2=M_shitfed[17] 
Xi_31 OR3_X1 $PINS ZN=n_7 A1=n_8 A2=M_shitfed[18] A3=M_shitfed[19] 
Xi_30 OR3_X1 $PINS ZN=n_6 A1=n_7 A2=M_shitfed[20] A3=M_shitfed[21] 
Xi_29 OR3_X1 $PINS ZN=p_0[31] A1=n_6 A2=M_shitfed[22] A3=M_shitfed[23] 
Xi_28 OAI21_X1 $PINS ZN=n_5 A=M_shitfed[23] B1=n_6 B2=M_shitfed[22] 
Xi_27 AND2_X1 $PINS ZN=p_0[23] A1=p_0[31] A2=n_5 
Xi_26 XOR2_X1 $PINS Z=p_0[22] A=M_shitfed[22] B=n_6 
Xi_25 OAI21_X1 $PINS ZN=n_4 A=M_shitfed[21] B1=n_7 B2=M_shitfed[20] 
Xi_24 AND2_X1 $PINS ZN=p_0[21] A1=n_6 A2=n_4 
Xi_23 XOR2_X1 $PINS Z=p_0[20] A=M_shitfed[20] B=n_7 
Xi_22 OAI21_X1 $PINS ZN=n_3 A=M_shitfed[19] B1=n_8 B2=M_shitfed[18] 
Xi_21 AND2_X1 $PINS ZN=p_0[19] A1=n_7 A2=n_3 
Xi_20 XOR2_X1 $PINS Z=p_0[18] A=M_shitfed[18] B=n_8 
Xi_19 XOR2_X1 $PINS Z=p_0[17] A=M_shitfed[17] B=n_9 
Xi_18 XOR2_X1 $PINS Z=p_0[16] A=M_shitfed[16] B=n_10 
Xi_17 XNOR2_X1 $PINS ZN=p_0[15] A=M_shitfed[15] B=n_11 
Xi_16 XNOR2_X1 $PINS ZN=p_0[14] A=M_shitfed[14] B=n_12 
Xi_15 XOR2_X1 $PINS Z=p_0[13] A=M_shitfed[13] B=n_13 
Xi_14 XOR2_X1 $PINS Z=p_0[12] A=M_shitfed[12] B=n_14 
Xi_13 XNOR2_X1 $PINS ZN=p_0[11] A=M_shitfed[11] B=n_15 
Xi_12 XOR2_X1 $PINS Z=p_0[10] A=M_shitfed[10] B=n_16 
Xi_11 OAI21_X1 $PINS ZN=n_2 A=M_shitfed[9] B1=n_17 B2=M_shitfed[8] 
Xi_10 AND2_X1 $PINS ZN=p_0[9] A1=n_16 A2=n_2 
Xi_9 XOR2_X1 $PINS Z=p_0[8] A=M_shitfed[8] B=n_17 
Xi_8 XOR2_X1 $PINS Z=p_0[7] A=M_shitfed[7] B=n_18 
Xi_7 OAI21_X1 $PINS ZN=n_1 A=M_shitfed[6] B1=n_19 B2=M_shitfed[5] 
Xi_6 AND2_X1 $PINS ZN=p_0[6] A1=n_18 A2=n_1 
Xi_5 XOR2_X1 $PINS Z=p_0[5] A=M_shitfed[5] B=n_19 
Xi_4 XOR2_X1 $PINS Z=p_0[4] A=M_shitfed[4] B=n_20 
Xi_3 XOR2_X1 $PINS Z=p_0[3] A=M_shitfed[3] B=n_21 
Xi_2 OAI21_X1 $PINS ZN=n_0 A=M_shitfed[2] B1=M_shitfed[1] B2=M_shitfed[0] 
Xi_1 AND2_X1 $PINS ZN=p_0[2] A1=n_21 A2=n_0 
Xi_0 XOR2_X1 $PINS Z=p_0[1] A=M_shitfed[1] B=M_shitfed[0] 
.ENDS

.SUBCKT datapath__0_7 M_result[31] M_result[30] M_result[29] M_result[28] 
+ M_result[27] M_result[26] M_result[25] M_result[24] M_result[23] M_result[22] 
+ M_result[21] M_result[20] M_result[19] M_result[18] M_result[17] M_result[16] 
+ M_result[15] M_result[14] M_result[13] M_result[12] M_result[11] M_result[10] 
+ M_result[9] M_result[8] M_result[7] M_result[6] M_result[5] M_result[4] 
+ M_result[3] M_result[2] M_result[1] M_result[0] p_0[31] p_0[30] p_0[29] 
+ p_0[28] p_0[27] p_0[26] p_0[25] p_0[24] p_0[23] p_0[22] p_0[21] p_0[20] 
+ p_0[19] p_0[18] p_0[17] p_0[16] p_0[15] p_0[14] p_0[13] p_0[12] p_0[11] 
+ p_0[10] p_0[9] p_0[8] p_0[7] p_0[6] p_0[5] p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] 
Xi_53 INV_X1 $PINS ZN=n_27 A=M_result[16] 
Xi_52 INV_X1 $PINS ZN=n_26 A=M_result[14] 
Xi_51 INV_X1 $PINS ZN=n_25 A=M_result[11] 
Xi_50 OR3_X1 $PINS ZN=n_24 A1=M_result[2] A2=M_result[1] A3=M_result[0] 
Xi_49 OR2_X1 $PINS ZN=n_23 A1=n_24 A2=M_result[3] 
Xi_48 OR2_X1 $PINS ZN=n_22 A1=n_23 A2=M_result[4] 
Xi_47 OR3_X1 $PINS ZN=n_21 A1=n_22 A2=M_result[5] A3=M_result[6] 
Xi_46 OR2_X1 $PINS ZN=n_20 A1=n_21 A2=M_result[7] 
Xi_45 OR3_X1 $PINS ZN=n_19 A1=n_20 A2=M_result[8] A3=M_result[9] 
Xi_44 NOR2_X1 $PINS ZN=n_18 A1=n_19 A2=M_result[10] 
Xi_43 NAND2_X1 $PINS ZN=n_17 A1=n_18 A2=n_25 
Xi_42 NOR2_X1 $PINS ZN=n_16 A1=n_17 A2=M_result[12] 
Xi_41 NOR3_X1 $PINS ZN=n_15 A1=n_17 A2=M_result[12] A3=M_result[13] 
Xi_40 NAND2_X1 $PINS ZN=n_14 A1=n_15 A2=n_26 
Xi_39 NOR2_X1 $PINS ZN=n_13 A1=n_14 A2=M_result[15] 
Xi_38 NAND2_X1 $PINS ZN=n_12 A1=n_13 A2=n_27 
Xi_37 OR2_X1 $PINS ZN=n_11 A1=n_12 A2=M_result[17] 
Xi_36 OR2_X1 $PINS ZN=n_10 A1=n_11 A2=M_result[18] 
Xi_35 NOR3_X1 $PINS ZN=n_9 A1=n_10 A2=M_result[19] A3=M_result[20] 
Xi_34 INV_X1 $PINS ZN=n_8 A=n_9 
Xi_33 OR3_X1 $PINS ZN=n_7 A1=n_8 A2=M_result[21] A3=M_result[22] 
Xi_32 NOR2_X1 $PINS ZN=n_6 A1=n_7 A2=M_result[23] 
Xi_31 NOR3_X1 $PINS ZN=n_5 A1=n_7 A2=M_result[23] A3=M_result[24] 
Xi_30 XNOR2_X1 $PINS ZN=p_0[25] A=M_result[25] B=n_5 
Xi_29 XNOR2_X1 $PINS ZN=p_0[24] A=M_result[24] B=n_6 
Xi_28 XOR2_X1 $PINS Z=p_0[23] A=M_result[23] B=n_7 
Xi_27 OAI21_X1 $PINS ZN=n_4 A=M_result[22] B1=n_8 B2=M_result[21] 
Xi_26 AND2_X1 $PINS ZN=p_0[22] A1=n_7 A2=n_4 
Xi_25 XNOR2_X1 $PINS ZN=p_0[21] A=M_result[21] B=n_9 
Xi_24 OAI21_X1 $PINS ZN=n_3 A=M_result[20] B1=n_10 B2=M_result[19] 
Xi_23 AND2_X1 $PINS ZN=p_0[20] A1=n_8 A2=n_3 
Xi_22 XOR2_X1 $PINS Z=p_0[19] A=M_result[19] B=n_10 
Xi_21 XOR2_X1 $PINS Z=p_0[18] A=M_result[18] B=n_11 
Xi_20 XOR2_X1 $PINS Z=p_0[17] A=M_result[17] B=n_12 
Xi_19 XNOR2_X1 $PINS ZN=p_0[16] A=M_result[16] B=n_13 
Xi_18 XOR2_X1 $PINS Z=p_0[15] A=M_result[15] B=n_14 
Xi_17 XNOR2_X1 $PINS ZN=p_0[14] A=M_result[14] B=n_15 
Xi_16 XNOR2_X1 $PINS ZN=p_0[13] A=M_result[13] B=n_16 
Xi_15 XOR2_X1 $PINS Z=p_0[12] A=M_result[12] B=n_17 
Xi_14 XNOR2_X1 $PINS ZN=p_0[11] A=M_result[11] B=n_18 
Xi_13 XOR2_X1 $PINS Z=p_0[10] A=M_result[10] B=n_19 
Xi_12 OAI21_X1 $PINS ZN=n_2 A=M_result[9] B1=n_20 B2=M_result[8] 
Xi_11 AND2_X1 $PINS ZN=p_0[9] A1=n_19 A2=n_2 
Xi_10 XOR2_X1 $PINS Z=p_0[8] A=M_result[8] B=n_20 
Xi_9 XOR2_X1 $PINS Z=p_0[7] A=M_result[7] B=n_21 
Xi_8 OAI21_X1 $PINS ZN=n_1 A=M_result[6] B1=n_22 B2=M_result[5] 
Xi_7 AND2_X1 $PINS ZN=p_0[6] A1=n_21 A2=n_1 
Xi_6 XOR2_X1 $PINS Z=p_0[5] A=M_result[5] B=n_22 
Xi_5 XOR2_X1 $PINS Z=p_0[4] A=M_result[4] B=n_23 
Xi_4 XOR2_X1 $PINS Z=p_0[3] A=M_result[3] B=n_24 
Xi_3 OAI21_X1 $PINS ZN=n_0 A=M_result[2] B1=M_result[1] B2=M_result[0] 
Xi_2 AND2_X1 $PINS ZN=p_0[2] A1=n_24 A2=n_0 
Xi_1 XOR2_X1 $PINS Z=p_0[1] A=M_result[1] B=M_result[0] 
Xi_0 NOR2_X1 $PINS ZN=p_0[28] A1=M_result[25] A2=n_5 
.ENDS

.SUBCKT datapath__0_1 B[31] B[30] B[29] B[28] B[27] B[26] B[25] B[24] B[23] 
+ B[22] B[21] B[20] B[19] B[18] B[17] B[16] B[15] B[14] B[13] B[12] B[11] B[10] 
+ B[9] B[8] B[7] B[6] B[5] B[4] B[3] B[2] B[1] B[0] CIN A[31] A[30] A[29] A[28] 
+ A[27] A[26] A[25] A[24] A[23] A[22] A[21] A[20] A[19] A[18] A[17] A[16] A[15] 
+ A[14] A[13] A[12] A[11] A[10] A[9] A[8] A[7] A[6] A[5] A[4] A[3] A[2] A[1] 
+ A[0] p_0[32] p_0[31] p_0[30] p_0[29] p_0[28] p_0[27] p_0[26] p_0[25] p_0[24] 
+ p_0[23] p_0[22] p_0[21] p_0[20] p_0[19] p_0[18] p_0[17] p_0[16] p_0[15] 
+ p_0[14] p_0[13] p_0[12] p_0[11] p_0[10] p_0[9] p_0[8] p_0[7] p_0[6] p_0[5] 
+ p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] 
Xi_25 FA_X1 $PINS CO=n_25 S=CLOCK_spc__n1 A=B[25] B=A[25] CI=n_24 
Xi_24 FA_X1 $PINS CO=n_24 S=p_0[24] A=B[25] B=A[25] CI=n_23 
Xi_23 FA_X1 $PINS CO=n_23 S=p_0[23] A=B[23] B=A[23] CI=n_22 
Xi_22 FA_X1 $PINS CO=n_22 S=p_0[22] A=B[22] B=A[22] CI=n_21 
Xi_21 FA_X1 $PINS CO=n_21 S=p_0[21] A=B[21] B=A[21] CI=n_20 
Xi_20 FA_X1 $PINS CO=n_20 S=p_0[20] A=B[20] B=A[20] CI=n_19 
Xi_19 FA_X1 $PINS CO=n_19 S=p_0[19] A=B[19] B=A[19] CI=n_18 
Xi_18 FA_X1 $PINS CO=n_18 S=p_0[18] A=B[18] B=A[18] CI=n_17 
Xi_17 FA_X1 $PINS CO=n_17 S=p_0[17] A=B[17] B=A[17] CI=n_16 
Xi_16 FA_X1 $PINS CO=n_16 S=p_0[16] A=B[16] B=A[16] CI=n_15 
Xi_15 FA_X1 $PINS CO=n_15 S=p_0[15] A=B[15] B=A[15] CI=n_14 
Xi_14 FA_X1 $PINS CO=n_14 S=p_0[14] A=B[14] B=A[14] CI=n_13 
Xi_13 FA_X1 $PINS CO=n_13 S=p_0[13] A=B[13] B=A[13] CI=n_12 
Xi_12 FA_X1 $PINS CO=n_12 S=p_0[12] A=B[12] B=A[12] CI=n_11 
Xi_11 FA_X1 $PINS CO=n_11 S=p_0[11] A=B[11] B=A[11] CI=n_10 
Xi_10 FA_X1 $PINS CO=n_10 S=p_0[10] A=B[10] B=A[10] CI=n_9 
Xi_9 FA_X1 $PINS CO=n_9 S=p_0[9] A=B[9] B=A[9] CI=n_8 
Xi_8 FA_X1 $PINS CO=n_8 S=p_0[8] A=B[8] B=A[8] CI=n_7 
Xi_7 FA_X1 $PINS CO=n_7 S=p_0[7] A=B[7] B=A[7] CI=n_6 
Xi_6 FA_X1 $PINS CO=n_6 S=p_0[6] A=B[6] B=A[6] CI=n_5 
Xi_5 FA_X1 $PINS CO=n_5 S=p_0[5] A=B[5] B=A[5] CI=n_4 
Xi_4 FA_X1 $PINS CO=n_4 S=p_0[4] A=B[4] B=A[4] CI=n_3 
Xi_3 FA_X1 $PINS CO=n_3 S=p_0[3] A=B[3] B=A[3] CI=n_2 
Xi_2 FA_X1 $PINS CO=n_2 S=p_0[2] A=B[2] B=A[2] CI=n_1 
Xi_1 FA_X1 $PINS CO=n_1 S=p_0[1] A=B[1] B=A[1] CI=n_0 
Xi_0 FA_X1 $PINS CO=n_0 S=p_0[0] A=VSS B=A[0] CI=B[0] 
XCLOCK_spc__c1 CLKBUF_X2 $PINS Z=p_0[25] A=CLOCK_spc__n1 
.ENDS

.SUBCKT VA__parameterized0 A[31] A[30] A[29] A[28] A[27] A[26] A[25] A[24] 
+ A[23] A[22] A[21] A[20] A[19] A[18] A[17] A[16] A[15] A[14] A[13] A[12] A[11] 
+ A[10] A[9] A[8] A[7] A[6] A[5] A[4] A[3] A[2] A[1] A[0] B[31] B[30] B[29] 
+ B[28] B[27] B[26] B[25] B[24] B[23] B[22] B[21] B[20] B[19] B[18] B[17] B[16] 
+ B[15] B[14] B[13] B[12] B[11] B[10] B[9] B[8] B[7] B[6] B[5] B[4] B[3] B[2] 
+ B[1] B[0] CIN SUM[31] SUM[30] SUM[29] SUM[28] SUM[27] SUM[26] SUM[25] SUM[24] 
+ SUM[23] SUM[22] SUM[21] SUM[20] SUM[19] SUM[18] SUM[17] SUM[16] SUM[15] 
+ SUM[14] SUM[13] SUM[12] SUM[11] SUM[10] SUM[9] SUM[8] SUM[7] SUM[6] SUM[5] 
+ SUM[4] SUM[3] SUM[2] SUM[1] SUM[0] COUT OVF 
Xi_0 datapath__0_1 $PINS p_0[32]=uc_14 p_0[31]=uc_15 p_0[30]=uc_16 
+ p_0[29]=uc_17 p_0[28]=uc_18 p_0[27]=uc_19 p_0[26]=uc_20 p_0[25]=SUM[31] 
+ p_0[24]=SUM[24] p_0[23]=SUM[23] p_0[22]=SUM[22] p_0[21]=SUM[21] p_0[20]=SUM[20] 
+ p_0[19]=SUM[19] p_0[18]=SUM[18] p_0[17]=SUM[17] p_0[16]=SUM[16] p_0[15]=SUM[15] 
+ p_0[14]=SUM[14] p_0[13]=SUM[13] p_0[12]=SUM[12] p_0[11]=SUM[11] p_0[10]=SUM[10] 
+ p_0[9]=SUM[9] p_0[8]=SUM[8] p_0[7]=SUM[7] p_0[6]=SUM[6] p_0[5]=SUM[5] 
+ p_0[4]=SUM[4] p_0[3]=SUM[3] p_0[2]=SUM[2] p_0[1]=SUM[1] p_0[0]=SUM[0] 
+ A[31]=uc_7 A[30]=uc_8 A[29]=uc_9 A[28]=uc_10 A[27]=uc_11 A[26]=uc_12 
+ A[25]=A[31] A[24]=uc_13 A[23]=A[23] A[22]=A[22] A[21]=A[21] A[20]=A[20] 
+ A[19]=A[19] A[18]=A[18] A[17]=A[17] A[16]=A[16] A[15]=A[15] A[14]=A[14] 
+ A[13]=A[13] A[12]=A[12] A[11]=A[11] A[10]=A[10] A[9]=A[9] A[8]=A[8] A[7]=A[7] 
+ A[6]=A[6] A[5]=A[5] A[4]=A[4] A[3]=A[3] A[2]=A[2] A[1]=A[1] A[0]=A[0] 
+ B[31]=uc_0 B[30]=uc_1 B[29]=uc_2 B[28]=uc_3 B[27]=uc_4 B[26]=uc_5 B[25]=B[31] 
+ B[24]=uc_6 B[23]=B[23] B[22]=B[22] B[21]=B[21] B[20]=B[20] B[19]=B[19] 
+ B[18]=B[18] B[17]=B[17] B[16]=B[16] B[15]=B[15] B[14]=B[14] B[13]=B[13] 
+ B[12]=B[12] B[11]=B[11] B[10]=B[10] B[9]=B[9] B[8]=B[8] B[7]=B[7] B[6]=B[6] 
+ B[5]=B[5] B[4]=B[4] B[3]=B[3] B[2]=B[2] B[1]=B[1] B[0]=B[0] 
.ENDS

.SUBCKT datapath B[7] B[6] B[5] B[4] B[3] B[2] B[1] B[0] CIN A[7] A[6] A[5] 
+ A[4] A[3] A[2] A[1] A[0] p_0[8] p_0[7] p_0[6] p_0[5] p_0[4] p_0[3] p_0[2] 
+ p_0[1] p_0[0] 
Xi_7 FA_X1 $PINS CO=n_7 S=p_0[7] A=B[7] B=A[7] CI=n_6 
Xi_6 FA_X1 $PINS CO=n_6 S=p_0[6] A=B[6] B=A[6] CI=n_5 
Xi_5 FA_X1 $PINS CO=n_5 S=p_0[5] A=B[5] B=A[5] CI=n_4 
Xi_4 FA_X1 $PINS CO=n_4 S=p_0[4] A=B[4] B=A[4] CI=n_3 
Xi_3 FA_X1 $PINS CO=n_3 S=p_0[3] A=B[3] B=A[3] CI=n_2 
Xi_2 FA_X1 $PINS CO=n_2 S=p_0[2] A=B[2] B=A[2] CI=n_1 
Xi_1 FA_X1 $PINS CO=n_1 S=p_0[1] A=B[1] B=A[1] CI=n_0 
Xi_0 FA_X1 $PINS CO=n_0 S=p_0[0] A=VSS B=A[0] CI=B[0] 
.ENDS

.SUBCKT VA A[7] A[6] A[5] A[4] A[3] A[2] A[1] A[0] B[7] B[6] B[5] B[4] B[3] 
+ B[2] B[1] B[0] CIN SUM[7] SUM[6] SUM[5] SUM[4] SUM[3] SUM[2] SUM[1] SUM[0] 
+ COUT OVF 
Xi_0 datapath $PINS p_0[8]=uc_0 p_0[7]=SUM[7] p_0[6]=SUM[6] p_0[5]=SUM[5] 
+ p_0[4]=SUM[4] p_0[3]=SUM[3] p_0[2]=SUM[2] p_0[1]=SUM[1] p_0[0]=SUM[0] A[7]=A[7] 
+ A[6]=A[6] A[5]=A[5] A[4]=A[4] A[3]=A[3] A[2]=A[2] A[1]=A[1] A[0]=A[0] B[7]=B[7] 
+ B[6]=B[6] B[5]=B[5] B[4]=B[4] B[3]=B[3] B[2]=B[2] B[1]=B[1] B[0]=B[0] 
.ENDS

.SUBCKT FPU_VA A[31] A[30] A[29] A[28] A[27] A[26] A[25] A[24] A[23] A[22] 
+ A[21] A[20] A[19] A[18] A[17] A[16] A[15] A[14] A[13] A[12] A[11] A[10] A[9] 
+ A[8] A[7] A[6] A[5] A[4] A[3] A[2] A[1] A[0] B[31] B[30] B[29] B[28] B[27] 
+ B[26] B[25] B[24] B[23] B[22] B[21] B[20] B[19] B[18] B[17] B[16] B[15] B[14] 
+ B[13] B[12] B[11] B[10] B[9] B[8] B[7] B[6] B[5] B[4] B[3] B[2] B[1] B[0] 
+ SUM[31] SUM[30] SUM[29] SUM[28] SUM[27] SUM[26] SUM[25] SUM[24] SUM[23] 
+ SUM[22] SUM[21] SUM[20] SUM[19] SUM[18] SUM[17] SUM[16] SUM[15] SUM[14] 
+ SUM[13] SUM[12] SUM[11] SUM[10] SUM[9] SUM[8] SUM[7] SUM[6] SUM[5] SUM[4] 
+ SUM[3] SUM[2] SUM[1] SUM[0] 
Xi_0_0_674 INV_X1 $PINS ZN=n_0_0_546 A=B[31] 
Xi_0_0_673 INV_X1 $PINS ZN=n_0_0_545 A=B[29] 
Xi_0_0_672 INV_X1 $PINS ZN=n_0_0_544 A=B[28] 
Xi_0_0_671 INV_X1 $PINS ZN=n_0_0_543 A=B[27] 
Xi_0_0_670 INV_X1 $PINS ZN=n_0_0_542 A=B[26] 
Xi_0_0_669 INV_X1 $PINS ZN=n_0_0_541 A=B[25] 
Xi_0_0_668 INV_X1 $PINS ZN=n_0_0_540 A=B[24] 
Xi_0_0_667 INV_X1 $PINS ZN=n_0_0_539 A=B[23] 
Xi_0_0_666 INV_X1 $PINS ZN=n_0_0_538 A=B[21] 
Xi_0_0_665 INV_X1 $PINS ZN=n_0_0_537 A=B[15] 
Xi_0_0_664 INV_X1 $PINS ZN=n_0_0_536 A=B[7] 
Xi_0_0_663 INV_X1 $PINS ZN=n_0_0_535 A=A[31] 
Xi_0_0_662 INV_X1 $PINS ZN=n_0_0_534 A=A[30] 
Xi_0_0_661 INV_X1 $PINS ZN=n_0_0_533 A=A[29] 
Xi_0_0_660 INV_X1 $PINS ZN=n_0_0_532 A=A[28] 
Xi_0_0_659 INV_X1 $PINS ZN=n_0_0_531 A=A[27] 
Xi_0_0_658 INV_X1 $PINS ZN=n_0_0_530 A=A[26] 
Xi_0_0_657 INV_X1 $PINS ZN=n_0_0_529 A=A[25] 
Xi_0_0_656 INV_X1 $PINS ZN=n_0_0_528 A=A[24] 
Xi_0_0_655 INV_X1 $PINS ZN=n_0_0_527 A=A[23] 
Xi_0_0_654 INV_X1 $PINS ZN=n_0_0_526 A=A[21] 
Xi_0_0_653 INV_X1 $PINS ZN=n_0_0_525 A=A[15] 
Xi_0_0_652 INV_X1 $PINS ZN=n_0_0_524 A=A[7] 
Xi_0_0_651 INV_X1 $PINS ZN=n_0_0_523 A=E_difference[3] 
Xi_0_0_650 INV_X1 $PINS ZN=n_0_0_522 A=E_difference[2] 
Xi_0_0_649 INV_X1 $PINS ZN=n_0_0_521 A=E_difference[1] 
Xi_0_0_648 INV_X1 $PINS ZN=n_0_0_520 A=E_difference[0] 
Xi_0_0_647 INV_X1 $PINS ZN=n_0_0_519 A=SUM[31] 
Xi_0_0_646 INV_X1 $PINS ZN=n_0_0_518 A=n_0_25 
Xi_0_0_645 INV_X1 $PINS ZN=n_0_0_517 A=n_0_45 
Xi_0_0_644 INV_X1 $PINS ZN=n_0_0_516 A=n_0_44 
Xi_0_0_643 INV_X1 $PINS ZN=n_0_0_515 A=n_0_42 
Xi_0_0_642 INV_X1 $PINS ZN=n_0_0_514 A=n_0_41 
Xi_0_0_641 INV_X1 $PINS ZN=n_0_0_513 A=n_0_40 
Xi_0_0_640 INV_X1 $PINS ZN=n_0_0_512 A=n_0_39 
Xi_0_0_639 INV_X1 $PINS ZN=n_0_0_511 A=n_0_38 
Xi_0_0_638 INV_X1 $PINS ZN=n_0_0_510 A=n_0_37 
Xi_0_0_637 INV_X1 $PINS ZN=n_0_0_509 A=n_0_36 
Xi_0_0_636 INV_X1 $PINS ZN=n_0_0_508 A=n_0_35 
Xi_0_0_635 INV_X1 $PINS ZN=n_0_0_507 A=n_0_34 
Xi_0_0_634 INV_X1 $PINS ZN=n_0_0_506 A=n_0_33 
Xi_0_0_633 INV_X1 $PINS ZN=n_0_0_505 A=n_0_32 
Xi_0_0_632 INV_X1 $PINS ZN=n_0_0_504 A=n_0_31 
Xi_0_0_631 INV_X1 $PINS ZN=n_0_0_503 A=n_0_30 
Xi_0_0_630 INV_X1 $PINS ZN=n_0_0_502 A=n_0_29 
Xi_0_0_629 INV_X1 $PINS ZN=n_0_0_501 A=n_0_28 
Xi_0_0_628 INV_X1 $PINS ZN=n_0_0_500 A=n_0_27 
Xi_0_0_627 INV_X1 $PINS ZN=n_0_0_499 A=n_0_26 
Xi_0_0_626 OR2_X1 $PINS ZN=n_0_126 A1=B[30] A2=A[30] 
Xi_0_0_625 AOI22_X1 $PINS ZN=n_0_0_498 A1=B[30] A2=n_0_0_534 B1=B[29] 
+ B2=n_0_0_533 
Xi_0_0_624 OAI22_X1 $PINS ZN=n_0_0_497 A1=B[28] A2=n_0_0_532 B1=B[29] 
+ B2=n_0_0_533 
Xi_0_0_623 OAI211_X1 $PINS ZN=n_0_0_496 A=n_0_0_539 B=A[23] C1=n_0_0_540 
+ C2=A[24] 
Xi_0_0_622 OAI221_X1 $PINS ZN=n_0_0_495 A=n_0_0_496 B1=B[24] B2=n_0_0_528 
+ C1=B[25] C2=n_0_0_529 
Xi_0_0_621 OAI221_X1 $PINS ZN=n_0_0_494 A=n_0_0_495 B1=n_0_0_542 B2=A[26] 
+ C1=n_0_0_541 C2=A[25] 
Xi_0_0_620 NOR2_X1 $PINS ZN=n_0_0_493 A1=B[27] A2=n_0_0_531 
Xi_0_0_619 INV_X1 $PINS ZN=n_0_0_492 A=n_0_0_493 
Xi_0_0_618 AOI21_X1 $PINS ZN=n_0_0_491 A=n_0_0_493 B1=n_0_0_542 B2=A[26] 
Xi_0_0_617 AOI222_X1 $PINS ZN=n_0_0_490 A1=B[27] A2=n_0_0_531 B1=B[28] 
+ B2=n_0_0_532 C1=n_0_0_494 C2=n_0_0_491 
Xi_0_0_616 OAI21_X1 $PINS ZN=n_0_0_489 A=n_0_0_498 B1=n_0_0_497 B2=n_0_0_490 
Xi_0_0_615 OAI21_X4 $PINS ZN=n_0_0_488 A=n_0_0_489 B1=B[30] B2=n_0_0_534 
Xi_0_0_614 INV_X1 $PINS ZN=n_0_0_487 A=n_0_0_488 
Xi_0_0_613 OAI22_X1 $PINS ZN=n_0_125 A1=n_0_0_533 A2=CLOCK_sps__n1 B1=n_0_0_545 
+ B2=n_0_0_488 
Xi_0_0_612 INV_X1 $PINS ZN=n_0_0_18 A=n_0_125 
Xi_0_0_611 OAI22_X1 $PINS ZN=n_0_124 A1=n_0_0_532 A2=CLOCK_sps__n1 B1=n_0_0_544 
+ B2=n_0_0_488 
Xi_0_0_610 INV_X1 $PINS ZN=n_0_0_486 A=n_0_124 
Xi_0_0_609 OAI22_X1 $PINS ZN=n_0_123 A1=n_0_0_531 A2=CLOCK_sps__n1 B1=n_0_0_543 
+ B2=n_0_0_488 
Xi_0_0_608 OAI22_X1 $PINS ZN=n_0_122 A1=n_0_0_530 A2=CLOCK_sps__n1 B1=n_0_0_542 
+ B2=n_0_0_488 
Xi_0_0_607 OAI22_X1 $PINS ZN=n_0_121 A1=n_0_0_529 A2=CLOCK_sps__n1 B1=n_0_0_541 
+ B2=n_0_0_488 
Xi_0_0_606 OAI22_X1 $PINS ZN=n_0_120 A1=n_0_0_528 A2=CLOCK_sps__n1 B1=n_0_0_540 
+ B2=n_0_0_488 
Xi_0_0_605 OAI22_X1 $PINS ZN=n_0_119 A1=n_0_0_527 A2=CLOCK_sps__n1 B1=n_0_0_539 
+ B2=n_0_0_488 
Xi_0_0_604 INV_X1 $PINS ZN=n_0_0_485 A=n_0_119 
Xi_0_0_603 NOR3_X4 $PINS ZN=n_0_0_484 A1=E_difference[7] A2=E_difference[6] 
+ A3=E_difference[5] 
Xi_0_0_602 NOR2_X1 $PINS ZN=n_0_0_483 A1=E_difference[4] A2=E_difference[3] 
Xi_0_0_601 INV_X1 $PINS ZN=n_0_0_482 A=n_0_0_483 
Xi_0_0_600 NOR2_X1 $PINS ZN=n_0_0_481 A1=E_difference[2] A2=n_0_0_482 
Xi_0_0_599 INV_X1 $PINS ZN=n_0_0_480 A=n_0_0_481 
Xi_0_0_598 AND2_X1 $PINS ZN=n_0_0_479 A1=n_0_0_484 A2=n_0_0_481 
Xi_0_0_597 NAND2_X1 $PINS ZN=n_0_0_478 A1=n_0_0_521 A2=n_0_0_479 
Xi_0_0_596 NOR2_X1 $PINS ZN=M_shitfed[23] A1=E_difference[0] A2=n_0_0_478 
Xi_0_0_595 AOI22_X1 $PINS ZN=n_0_0_477 A1=B[22] A2=n_0_0_488 B1=A[22] 
+ B2=n_0_0_487 
Xi_0_0_594 AOI21_X1 $PINS ZN=M_shitfed[22] A=n_0_0_478 B1=n_0_0_520 
+ B2=n_0_0_477 
Xi_0_0_593 OAI22_X1 $PINS ZN=n_0_0_476 A1=n_0_0_538 A2=CLOCK_sps__n1 
+ B1=n_0_0_526 B2=n_0_0_488 
Xi_0_0_592 INV_X1 $PINS ZN=n_0_0_475 A=n_0_0_476 
Xi_0_0_591 NOR2_X1 $PINS ZN=n_0_0_474 A1=E_difference[1] A2=n_0_0_476 
Xi_0_0_590 NOR2_X1 $PINS ZN=n_0_0_473 A1=E_difference[1] A2=n_0_0_477 
Xi_0_0_589 OAI21_X1 $PINS ZN=n_0_0_472 A=n_0_0_479 B1=n_0_0_520 B2=n_0_0_473 
Xi_0_0_588 AOI21_X1 $PINS ZN=M_shitfed[21] A=n_0_0_472 B1=n_0_0_520 
+ B2=n_0_0_474 
Xi_0_0_587 AOI22_X1 $PINS ZN=n_0_0_471 A1=B[20] A2=n_0_0_488 B1=A[20] 
+ B2=n_0_0_487 
Xi_0_0_586 AOI221_X1 $PINS ZN=n_0_0_470 A=n_0_0_480 B1=n_0_0_521 B2=n_0_0_471 
+ C1=E_difference[1] C2=n_0_0_477 
Xi_0_0_585 OAI21_X1 $PINS ZN=n_0_0_469 A=E_difference[0] B1=n_0_0_480 
+ B2=n_0_0_474 
Xi_0_0_584 OAI211_X1 $PINS ZN=n_0_0_468 A=n_0_0_484 B=n_0_0_469 
+ C1=E_difference[0] C2=n_0_0_470 
Xi_0_0_583 INV_X1 $PINS ZN=M_shitfed[20] A=n_0_0_468 
Xi_0_0_582 AOI22_X1 $PINS ZN=n_0_0_467 A1=B[19] A2=CLOCK_spc__n3 B1=A[19] 
+ B2=n_0_0_487 
Xi_0_0_581 NOR2_X1 $PINS ZN=n_0_0_466 A1=n_0_0_482 A2=n_0_0_467 
Xi_0_0_580 NOR2_X1 $PINS ZN=n_0_0_465 A1=n_0_0_522 A2=n_0_0_482 
Xi_0_0_579 INV_X1 $PINS ZN=n_0_0_464 A=n_0_0_465 
Xi_0_0_578 NOR2_X1 $PINS ZN=n_0_0_463 A1=n_0_0_466 A2=n_0_0_465 
Xi_0_0_577 NAND2_X1 $PINS ZN=n_0_0_462 A1=E_difference[1] A2=n_0_0_481 
Xi_0_0_576 OAI22_X1 $PINS ZN=n_0_0_461 A1=E_difference[1] A2=n_0_0_463 
+ B1=n_0_0_475 B2=n_0_0_462 
Xi_0_0_575 OAI221_X1 $PINS ZN=n_0_0_460 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_470 
+ C1=E_difference[0] C2=n_0_0_461 
Xi_0_0_574 INV_X1 $PINS ZN=M_shitfed[19] A=n_0_0_460 
Xi_0_0_573 AOI22_X1 $PINS ZN=n_0_0_459 A1=B[18] A2=n_0_0_488 B1=A[18] 
+ B2=n_0_0_487 
Xi_0_0_572 OAI22_X1 $PINS ZN=n_0_0_458 A1=n_0_0_477 A2=n_0_0_464 B1=n_0_0_480 
+ B2=n_0_0_459 
Xi_0_0_571 INV_X1 $PINS ZN=n_0_0_457 A=n_0_0_458 
Xi_0_0_570 OAI22_X1 $PINS ZN=n_0_0_456 A1=E_difference[1] A2=n_0_0_457 
+ B1=n_0_0_471 B2=n_0_0_462 
Xi_0_0_569 OAI221_X1 $PINS ZN=n_0_0_455 A=n_0_0_484 B1=E_difference[0] 
+ B2=n_0_0_456 C1=n_0_0_520 C2=n_0_0_461 
Xi_0_0_568 INV_X1 $PINS ZN=M_shitfed[18] A=n_0_0_455 
Xi_0_0_567 AOI22_X1 $PINS ZN=n_0_0_454 A1=B[17] A2=n_0_0_488 B1=A[17] 
+ B2=n_0_0_487 
Xi_0_0_566 OAI22_X1 $PINS ZN=n_0_0_453 A1=n_0_0_475 A2=n_0_0_464 B1=n_0_0_480 
+ B2=n_0_0_454 
Xi_0_0_565 INV_X1 $PINS ZN=n_0_0_452 A=n_0_0_453 
Xi_0_0_564 OAI22_X1 $PINS ZN=n_0_0_451 A1=n_0_0_521 A2=n_0_0_463 
+ B1=E_difference[1] B2=n_0_0_452 
Xi_0_0_563 OAI221_X1 $PINS ZN=n_0_0_450 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_456 
+ C1=E_difference[0] C2=n_0_0_451 
Xi_0_0_562 INV_X1 $PINS ZN=M_shitfed[17] A=n_0_0_450 
Xi_0_0_561 AOI22_X1 $PINS ZN=n_0_0_449 A1=B[16] A2=n_0_0_488 B1=A[16] 
+ B2=n_0_0_487 
Xi_0_0_560 OAI22_X1 $PINS ZN=n_0_0_448 A1=n_0_0_480 A2=n_0_0_449 B1=n_0_0_471 
+ B2=n_0_0_464 
Xi_0_0_559 INV_X1 $PINS ZN=n_0_0_447 A=n_0_0_448 
Xi_0_0_558 OAI22_X1 $PINS ZN=n_0_0_446 A1=n_0_0_521 A2=n_0_0_457 
+ B1=E_difference[1] B2=n_0_0_447 
Xi_0_0_557 OAI221_X1 $PINS ZN=n_0_0_445 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_451 
+ C1=E_difference[0] C2=n_0_0_446 
Xi_0_0_556 INV_X1 $PINS ZN=M_shitfed[16] A=n_0_0_445 
Xi_0_0_555 NOR2_X1 $PINS ZN=n_0_0_444 A1=E_difference[4] A2=n_0_0_523 
Xi_0_0_554 INV_X1 $PINS ZN=n_0_0_443 A=n_0_0_444 
Xi_0_0_553 AOI221_X1 $PINS ZN=n_0_0_442 A=E_difference[4] B1=n_0_0_537 
+ B2=n_0_0_488 C1=n_0_0_525 C2=n_0_0_487 
Xi_0_0_552 OR2_X1 $PINS ZN=n_0_0_441 A1=n_0_0_444 A2=n_0_0_442 
Xi_0_0_551 AOI22_X1 $PINS ZN=n_0_0_440 A1=n_0_0_522 A2=n_0_0_441 
+ B1=E_difference[2] B2=n_0_0_466 
Xi_0_0_550 OAI22_X1 $PINS ZN=n_0_0_439 A1=n_0_0_521 A2=n_0_0_452 
+ B1=E_difference[1] B2=n_0_0_440 
Xi_0_0_549 OAI221_X1 $PINS ZN=n_0_0_438 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_446 
+ C1=E_difference[0] C2=n_0_0_439 
Xi_0_0_548 INV_X1 $PINS ZN=M_shitfed[15] A=n_0_0_438 
Xi_0_0_547 AOI22_X1 $PINS ZN=n_0_0_437 A1=B[14] A2=n_0_0_488 B1=A[14] 
+ B2=n_0_0_487 
Xi_0_0_546 OAI22_X1 $PINS ZN=n_0_0_436 A1=n_0_0_477 A2=n_0_0_443 B1=n_0_0_482 
+ B2=n_0_0_437 
Xi_0_0_545 NOR2_X1 $PINS ZN=n_0_0_435 A1=n_0_0_464 A2=n_0_0_459 
Xi_0_0_544 AOI21_X1 $PINS ZN=n_0_0_434 A=n_0_0_435 B1=n_0_0_522 B2=n_0_0_436 
Xi_0_0_543 OAI22_X1 $PINS ZN=n_0_0_433 A1=E_difference[1] A2=n_0_0_434 
+ B1=n_0_0_521 B2=n_0_0_447 
Xi_0_0_542 OAI221_X1 $PINS ZN=n_0_0_432 A=n_0_0_484 B1=E_difference[0] 
+ B2=n_0_0_433 C1=n_0_0_520 C2=n_0_0_439 
Xi_0_0_541 INV_X1 $PINS ZN=M_shitfed[14] A=n_0_0_432 
Xi_0_0_540 AOI22_X1 $PINS ZN=n_0_0_431 A1=B[13] A2=n_0_0_488 B1=A[13] 
+ B2=n_0_0_487 
Xi_0_0_539 OAI22_X1 $PINS ZN=n_0_0_430 A1=n_0_0_475 A2=n_0_0_443 B1=n_0_0_482 
+ B2=n_0_0_431 
Xi_0_0_538 NOR2_X1 $PINS ZN=n_0_0_429 A1=n_0_0_464 A2=n_0_0_454 
Xi_0_0_537 AOI21_X1 $PINS ZN=n_0_0_428 A=n_0_0_429 B1=n_0_0_522 B2=n_0_0_430 
Xi_0_0_536 OAI22_X1 $PINS ZN=n_0_0_427 A1=E_difference[1] A2=n_0_0_428 
+ B1=n_0_0_521 B2=n_0_0_440 
Xi_0_0_535 OAI221_X1 $PINS ZN=n_0_0_426 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_433 
+ C1=E_difference[0] C2=n_0_0_427 
Xi_0_0_534 INV_X1 $PINS ZN=M_shitfed[13] A=n_0_0_426 
Xi_0_0_533 AOI22_X1 $PINS ZN=n_0_0_425 A1=B[12] A2=n_0_0_488 B1=A[12] 
+ B2=n_0_0_487 
Xi_0_0_532 OAI22_X1 $PINS ZN=n_0_0_424 A1=n_0_0_482 A2=n_0_0_425 B1=n_0_0_471 
+ B2=n_0_0_443 
Xi_0_0_531 NOR2_X1 $PINS ZN=n_0_0_423 A1=n_0_0_464 A2=n_0_0_449 
Xi_0_0_530 AOI21_X1 $PINS ZN=n_0_0_422 A=n_0_0_423 B1=n_0_0_522 B2=n_0_0_424 
Xi_0_0_529 OAI22_X1 $PINS ZN=n_0_0_421 A1=n_0_0_521 A2=n_0_0_434 
+ B1=E_difference[1] B2=n_0_0_422 
Xi_0_0_528 OAI221_X1 $PINS ZN=n_0_0_420 A=n_0_0_484 B1=E_difference[0] 
+ B2=n_0_0_421 C1=n_0_0_520 C2=n_0_0_427 
Xi_0_0_527 INV_X1 $PINS ZN=M_shitfed[12] A=n_0_0_420 
Xi_0_0_526 AOI22_X1 $PINS ZN=n_0_0_419 A1=B[11] A2=CLOCK_spc__n3 B1=A[11] 
+ B2=n_0_0_487 
Xi_0_0_525 OAI22_X1 $PINS ZN=n_0_0_418 A1=n_0_0_467 A2=n_0_0_443 B1=n_0_0_482 
+ B2=n_0_0_419 
Xi_0_0_524 AOI22_X1 $PINS ZN=n_0_0_417 A1=n_0_0_522 A2=n_0_0_418 
+ B1=E_difference[2] B2=n_0_0_441 
Xi_0_0_523 OAI22_X1 $PINS ZN=n_0_0_416 A1=E_difference[1] A2=n_0_0_417 
+ B1=n_0_0_521 B2=n_0_0_428 
Xi_0_0_522 OAI221_X1 $PINS ZN=n_0_0_415 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_421 
+ C1=E_difference[0] C2=n_0_0_416 
Xi_0_0_521 INV_X1 $PINS ZN=M_shitfed[11] A=n_0_0_415 
Xi_0_0_520 AOI22_X1 $PINS ZN=n_0_0_414 A1=B[10] A2=n_0_0_488 B1=A[10] 
+ B2=n_0_0_487 
Xi_0_0_519 OAI22_X1 $PINS ZN=n_0_0_413 A1=n_0_0_459 A2=n_0_0_443 B1=n_0_0_482 
+ B2=n_0_0_414 
Xi_0_0_518 AOI22_X1 $PINS ZN=n_0_0_412 A1=n_0_0_522 A2=n_0_0_413 
+ B1=E_difference[2] B2=n_0_0_436 
Xi_0_0_517 OAI22_X1 $PINS ZN=n_0_0_411 A1=n_0_0_521 A2=n_0_0_422 
+ B1=E_difference[1] B2=n_0_0_412 
Xi_0_0_516 OAI221_X1 $PINS ZN=n_0_0_410 A=n_0_0_484 B1=E_difference[0] 
+ B2=n_0_0_411 C1=n_0_0_520 C2=n_0_0_416 
Xi_0_0_515 INV_X1 $PINS ZN=M_shitfed[10] A=n_0_0_410 
Xi_0_0_514 AOI22_X1 $PINS ZN=n_0_0_409 A1=B[9] A2=CLOCK_spc__n3 B1=A[9] 
+ B2=n_0_0_487 
Xi_0_0_513 OAI22_X1 $PINS ZN=n_0_0_408 A1=n_0_0_454 A2=n_0_0_443 B1=n_0_0_482 
+ B2=n_0_0_409 
Xi_0_0_512 AOI22_X1 $PINS ZN=n_0_0_407 A1=E_difference[2] A2=n_0_0_430 
+ B1=n_0_0_522 B2=n_0_0_408 
Xi_0_0_511 OAI22_X1 $PINS ZN=n_0_0_406 A1=n_0_0_521 A2=n_0_0_417 
+ B1=E_difference[1] B2=n_0_0_407 
Xi_0_0_510 OAI221_X1 $PINS ZN=n_0_0_405 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_411 
+ C1=E_difference[0] C2=n_0_0_406 
Xi_0_0_509 INV_X1 $PINS ZN=M_shitfed[9] A=n_0_0_405 
Xi_0_0_508 AOI22_X1 $PINS ZN=n_0_0_404 A1=B[8] A2=CLOCK_spc__n3 B1=A[8] 
+ B2=n_0_0_487 
Xi_0_0_507 OAI22_X1 $PINS ZN=n_0_0_403 A1=n_0_0_449 A2=n_0_0_443 B1=n_0_0_482 
+ B2=n_0_0_404 
Xi_0_0_506 AOI22_X1 $PINS ZN=n_0_0_402 A1=E_difference[2] A2=n_0_0_424 
+ B1=n_0_0_522 B2=n_0_0_403 
Xi_0_0_505 OAI22_X1 $PINS ZN=n_0_0_401 A1=E_difference[1] A2=n_0_0_402 
+ B1=n_0_0_521 B2=n_0_0_412 
Xi_0_0_504 OAI221_X1 $PINS ZN=n_0_0_400 A=n_0_0_484 B1=E_difference[0] 
+ B2=n_0_0_401 C1=n_0_0_520 C2=n_0_0_406 
Xi_0_0_503 INV_X1 $PINS ZN=M_shitfed[8] A=n_0_0_400 
Xi_0_0_502 OAI221_X1 $PINS ZN=n_0_0_399 A=n_0_0_483 B1=n_0_0_524 B2=n_0_0_488 
+ C1=n_0_0_536 C2=n_0_0_487 
Xi_0_0_501 OAI21_X1 $PINS ZN=n_0_0_398 A=n_0_0_399 B1=n_0_0_523 B2=n_0_0_442 
Xi_0_0_500 INV_X1 $PINS ZN=n_0_0_397 A=n_0_0_398 
Xi_0_0_499 OAI22_X1 $PINS ZN=n_0_0_396 A1=E_difference[2] A2=n_0_0_397 
+ B1=n_0_0_522 B2=n_0_0_418 
Xi_0_0_498 AOI22_X1 $PINS ZN=n_0_0_395 A1=n_0_0_521 A2=n_0_0_396 
+ B1=E_difference[1] B2=n_0_0_407 
Xi_0_0_497 OAI221_X1 $PINS ZN=n_0_0_394 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_401 
+ C1=E_difference[0] C2=n_0_0_395 
Xi_0_0_496 INV_X1 $PINS ZN=M_shitfed[7] A=n_0_0_394 
Xi_0_0_495 OAI221_X1 $PINS ZN=n_0_0_393 A=n_0_0_483 B1=B[6] B2=n_0_0_487 
+ C1=A[6] C2=n_0_0_488 
Xi_0_0_494 NAND2_X1 $PINS ZN=n_0_0_392 A1=E_difference[4] A2=n_0_0_523 
Xi_0_0_493 OAI221_X1 $PINS ZN=n_0_0_391 A=n_0_0_393 B1=n_0_0_443 B2=n_0_0_437 
+ C1=n_0_0_477 C2=n_0_0_392 
Xi_0_0_492 AOI22_X1 $PINS ZN=n_0_0_390 A1=n_0_0_522 A2=n_0_0_391 
+ B1=E_difference[2] B2=n_0_0_413 
Xi_0_0_491 OAI22_X1 $PINS ZN=n_0_0_389 A1=E_difference[1] A2=n_0_0_390 
+ B1=n_0_0_521 B2=n_0_0_402 
Xi_0_0_490 OAI221_X1 $PINS ZN=n_0_0_388 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_395 
+ C1=E_difference[0] C2=n_0_0_389 
Xi_0_0_489 INV_X1 $PINS ZN=M_shitfed[6] A=n_0_0_388 
Xi_0_0_488 OAI221_X1 $PINS ZN=n_0_0_387 A=n_0_0_483 B1=B[5] B2=n_0_0_487 
+ C1=A[5] C2=n_0_0_488 
Xi_0_0_487 OAI221_X1 $PINS ZN=n_0_0_386 A=n_0_0_387 B1=n_0_0_443 B2=n_0_0_431 
+ C1=n_0_0_475 C2=n_0_0_392 
Xi_0_0_486 AOI22_X1 $PINS ZN=n_0_0_385 A1=E_difference[2] A2=n_0_0_408 
+ B1=n_0_0_522 B2=n_0_0_386 
Xi_0_0_485 AOI22_X1 $PINS ZN=n_0_0_384 A1=E_difference[1] A2=n_0_0_396 
+ B1=n_0_0_521 B2=n_0_0_385 
Xi_0_0_484 OAI221_X1 $PINS ZN=n_0_0_383 A=n_0_0_484 B1=E_difference[0] 
+ B2=n_0_0_384 C1=n_0_0_520 C2=n_0_0_389 
Xi_0_0_483 INV_X1 $PINS ZN=M_shitfed[5] A=n_0_0_383 
Xi_0_0_482 OAI221_X1 $PINS ZN=n_0_0_382 A=n_0_0_483 B1=B[4] B2=n_0_0_487 
+ C1=A[4] C2=n_0_0_488 
Xi_0_0_481 OAI221_X1 $PINS ZN=n_0_0_381 A=n_0_0_382 B1=n_0_0_471 B2=n_0_0_392 
+ C1=n_0_0_443 C2=n_0_0_425 
Xi_0_0_480 AOI22_X1 $PINS ZN=n_0_0_380 A1=E_difference[2] A2=n_0_0_403 
+ B1=n_0_0_522 B2=n_0_0_381 
Xi_0_0_479 OAI22_X1 $PINS ZN=n_0_0_379 A1=n_0_0_521 A2=n_0_0_390 
+ B1=E_difference[1] B2=n_0_0_380 
Xi_0_0_478 OAI221_X1 $PINS ZN=n_0_0_378 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_384 
+ C1=E_difference[0] C2=n_0_0_379 
Xi_0_0_477 INV_X1 $PINS ZN=M_shitfed[4] A=n_0_0_378 
Xi_0_0_476 OAI221_X1 $PINS ZN=n_0_0_377 A=n_0_0_483 B1=B[3] B2=n_0_0_487 
+ C1=A[3] C2=CLOCK_spc__n5 
Xi_0_0_475 OAI221_X1 $PINS ZN=n_0_0_376 A=n_0_0_377 B1=n_0_0_467 B2=n_0_0_392 
+ C1=n_0_0_443 C2=n_0_0_419 
Xi_0_0_474 AOI22_X1 $PINS ZN=n_0_0_375 A1=n_0_0_522 A2=n_0_0_376 
+ B1=E_difference[2] B2=n_0_0_397 
Xi_0_0_473 OAI22_X1 $PINS ZN=n_0_0_374 A1=n_0_0_521 A2=n_0_0_385 
+ B1=E_difference[1] B2=n_0_0_375 
Xi_0_0_472 OAI221_X1 $PINS ZN=n_0_0_373 A=n_0_0_484 B1=E_difference[0] 
+ B2=n_0_0_374 C1=n_0_0_520 C2=n_0_0_379 
Xi_0_0_471 INV_X1 $PINS ZN=M_shitfed[3] A=n_0_0_373 
Xi_0_0_470 OAI221_X1 $PINS ZN=n_0_0_372 A=n_0_0_483 B1=B[2] B2=n_0_0_487 
+ C1=A[2] C2=n_0_0_488 
Xi_0_0_469 OAI221_X1 $PINS ZN=n_0_0_371 A=n_0_0_372 B1=n_0_0_443 B2=n_0_0_414 
+ C1=n_0_0_459 C2=n_0_0_392 
Xi_0_0_468 AOI22_X1 $PINS ZN=n_0_0_370 A1=n_0_0_522 A2=n_0_0_371 
+ B1=E_difference[2] B2=n_0_0_391 
Xi_0_0_467 OAI22_X1 $PINS ZN=n_0_0_369 A1=n_0_0_521 A2=n_0_0_380 
+ B1=E_difference[1] B2=n_0_0_370 
Xi_0_0_466 OAI221_X1 $PINS ZN=n_0_0_368 A=n_0_0_484 B1=n_0_0_520 B2=n_0_0_374 
+ C1=E_difference[0] C2=n_0_0_369 
Xi_0_0_465 INV_X1 $PINS ZN=M_shitfed[2] A=n_0_0_368 
Xi_0_0_464 OAI21_X1 $PINS ZN=n_0_0_367 A=n_0_0_522 B1=n_0_0_443 B2=n_0_0_409 
Xi_0_0_463 OAI221_X1 $PINS ZN=n_0_0_366 A=n_0_0_483 B1=B[1] B2=n_0_0_487 
+ C1=A[1] C2=CLOCK_spc__n3 
Xi_0_0_462 OAI21_X1 $PINS ZN=n_0_0_365 A=n_0_0_366 B1=n_0_0_454 B2=n_0_0_392 
Xi_0_0_461 OAI22_X1 $PINS ZN=n_0_0_364 A1=n_0_0_522 A2=n_0_0_386 B1=n_0_0_367 
+ B2=n_0_0_365 
Xi_0_0_460 AOI22_X1 $PINS ZN=n_0_0_363 A1=n_0_0_521 A2=n_0_0_364 
+ B1=E_difference[1] B2=n_0_0_375 
Xi_0_0_459 OAI221_X1 $PINS ZN=n_0_0_362 A=n_0_0_484 B1=E_difference[0] 
+ B2=n_0_0_363 C1=n_0_0_520 C2=n_0_0_369 
Xi_0_0_458 INV_X1 $PINS ZN=M_shitfed[1] A=n_0_0_362 
Xi_0_0_457 OAI21_X1 $PINS ZN=n_0_0_361 A=n_0_0_522 B1=n_0_0_449 B2=n_0_0_392 
Xi_0_0_456 OAI221_X1 $PINS ZN=n_0_0_360 A=n_0_0_483 B1=B[0] B2=n_0_0_487 
+ C1=A[0] C2=CLOCK_spc__n3 
Xi_0_0_455 OAI21_X1 $PINS ZN=n_0_0_359 A=n_0_0_360 B1=n_0_0_443 B2=n_0_0_404 
Xi_0_0_454 OAI221_X1 $PINS ZN=n_0_0_358 A=n_0_0_521 B1=n_0_0_361 B2=n_0_0_359 
+ C1=n_0_0_522 C2=n_0_0_381 
Xi_0_0_453 OAI211_X1 $PINS ZN=n_0_0_357 A=n_0_0_520 B=n_0_0_358 C1=n_0_0_521 
+ C2=n_0_0_370 
Xi_0_0_452 OAI211_X1 $PINS ZN=n_0_0_356 A=n_0_0_484 B=n_0_0_357 C1=n_0_0_520 
+ C2=n_0_0_363 
Xi_0_0_451 INV_X1 $PINS ZN=M_shitfed[0] A=n_0_0_356 
Xi_0_0_450 NAND2_X1 $PINS ZN=n_0_0_355 A1=B[30] A2=A[30] 
Xi_0_0_449 OAI211_X1 $PINS ZN=n_0_0_354 A=B[23] B=n_0_0_527 C1=B[24] 
+ C2=n_0_0_528 
Xi_0_0_448 OAI221_X1 $PINS ZN=n_0_0_353 A=n_0_0_354 B1=n_0_0_540 B2=A[24] 
+ C1=n_0_0_541 C2=A[25] 
Xi_0_0_447 OAI221_X1 $PINS ZN=n_0_0_352 A=n_0_0_353 B1=B[25] B2=n_0_0_529 
+ C1=B[26] C2=n_0_0_530 
Xi_0_0_446 OAI221_X1 $PINS ZN=n_0_0_351 A=n_0_0_352 B1=n_0_0_542 B2=A[26] 
+ C1=n_0_0_543 C2=A[27] 
Xi_0_0_445 AOI22_X1 $PINS ZN=n_0_0_350 A1=B[28] A2=n_0_0_532 B1=n_0_0_492 
+ B2=n_0_0_351 
Xi_0_0_444 OAI21_X1 $PINS ZN=n_0_0_349 A=n_0_0_498 B1=n_0_0_497 B2=n_0_0_350 
Xi_0_0_443 OAI21_X1 $PINS ZN=n_0_0_348 A=n_0_0_349 B1=B[30] B2=n_0_0_534 
Xi_0_0_442 INV_X1 $PINS ZN=n_0_0_347 A=n_0_0_348 
Xi_0_0_441 OAI22_X1 $PINS ZN=n_0_0_346 A1=n_0_0_540 A2=n_0_0_347 B1=n_0_0_528 
+ B2=n_0_0_348 
Xi_0_0_440 OAI22_X1 $PINS ZN=E_smallest[0] A1=n_0_0_539 A2=n_0_0_347 
+ B1=n_0_0_527 B2=n_0_0_348 
Xi_0_0_439 NOR2_X1 $PINS ZN=n_0_0_345 A1=n_0_0_346 A2=E_smallest[0] 
Xi_0_0_438 INV_X1 $PINS ZN=n_0_0_344 A=n_0_0_345 
Xi_0_0_437 OAI22_X1 $PINS ZN=n_0_0_343 A1=n_0_0_541 A2=n_0_0_347 B1=n_0_0_529 
+ B2=n_0_0_348 
Xi_0_0_436 NOR2_X1 $PINS ZN=n_0_0_342 A1=n_0_0_344 A2=n_0_0_343 
Xi_0_0_435 INV_X1 $PINS ZN=n_0_0_341 A=n_0_0_342 
Xi_0_0_434 OAI22_X1 $PINS ZN=n_0_0_340 A1=n_0_0_542 A2=n_0_0_347 B1=n_0_0_530 
+ B2=n_0_0_348 
Xi_0_0_433 NOR2_X1 $PINS ZN=n_0_0_339 A1=n_0_0_341 A2=n_0_0_340 
Xi_0_0_432 INV_X1 $PINS ZN=n_0_0_338 A=n_0_0_339 
Xi_0_0_431 OAI22_X1 $PINS ZN=n_0_0_337 A1=n_0_0_543 A2=n_0_0_347 B1=n_0_0_531 
+ B2=n_0_0_348 
Xi_0_0_430 NOR2_X1 $PINS ZN=n_0_0_336 A1=n_0_0_338 A2=n_0_0_337 
Xi_0_0_429 INV_X1 $PINS ZN=n_0_0_335 A=n_0_0_336 
Xi_0_0_428 OAI22_X1 $PINS ZN=n_0_0_334 A1=n_0_0_544 A2=n_0_0_347 B1=n_0_0_532 
+ B2=n_0_0_348 
Xi_0_0_427 NOR2_X1 $PINS ZN=n_0_0_333 A1=n_0_0_335 A2=n_0_0_334 
Xi_0_0_426 INV_X1 $PINS ZN=n_0_0_332 A=n_0_0_333 
Xi_0_0_425 OAI22_X1 $PINS ZN=n_0_0_331 A1=n_0_0_545 A2=n_0_0_347 B1=n_0_0_533 
+ B2=n_0_0_348 
Xi_0_0_424 NOR2_X1 $PINS ZN=n_0_0_330 A1=n_0_0_332 A2=n_0_0_331 
Xi_0_0_423 XOR2_X1 $PINS Z=E_complement[7] A=n_0_0_355 B=n_0_0_330 
Xi_0_0_422 AOI21_X1 $PINS ZN=E_complement[6] A=n_0_0_330 B1=n_0_0_332 
+ B2=n_0_0_331 
Xi_0_0_421 AOI21_X1 $PINS ZN=E_complement[5] A=n_0_0_333 B1=n_0_0_335 
+ B2=n_0_0_334 
Xi_0_0_420 AOI21_X1 $PINS ZN=E_complement[4] A=n_0_0_336 B1=n_0_0_338 
+ B2=n_0_0_337 
Xi_0_0_419 AOI21_X1 $PINS ZN=E_complement[3] A=n_0_0_339 B1=n_0_0_341 
+ B2=n_0_0_340 
Xi_0_0_418 AOI21_X1 $PINS ZN=E_complement[2] A=n_0_0_342 B1=n_0_0_344 
+ B2=n_0_0_343 
Xi_0_0_417 AOI21_X1 $PINS ZN=E_complement[1] A=n_0_0_345 B1=n_0_0_346 
+ B2=E_smallest[0] 
Xi_0_0_416 OR2_X1 $PINS ZN=n_0_0_329 A1=SUM[31] A2=M_result[24] 
Xi_0_0_415 OR2_X1 $PINS ZN=n_0_0_328 A1=n_0_0_519 A2=n_0_24 
Xi_0_0_414 OR2_X1 $PINS ZN=n_0_0_327 A1=n_0_25 A2=n_0_23 
Xi_0_0_413 OAI21_X1 $PINS ZN=n_0_0_326 A=n_0_0_329 B1=n_0_0_328 B2=n_0_0_327 
Xi_0_0_412 OAI21_X1 $PINS ZN=n_0_0_325 A=n_0_0_326 B1=n_0_0_519 B2=n_0_0_518 
Xi_0_0_411 OAI22_X1 $PINS ZN=n_0_0_324 A1=n_0_0_519 A2=n_0_22 B1=SUM[31] 
+ B2=M_result[23] 
Xi_0_0_410 OAI22_X1 $PINS ZN=n_0_0_323 A1=n_0_0_519 A2=n_0_21 B1=SUM[31] 
+ B2=M_result[22] 
Xi_0_0_409 INV_X1 $PINS ZN=n_0_0_322 A=n_0_0_323 
Xi_0_0_408 AND2_X1 $PINS ZN=n_0_0_321 A1=n_0_0_324 A2=n_0_0_323 
Xi_0_0_407 OAI22_X1 $PINS ZN=n_0_0_320 A1=n_0_0_519 A2=n_0_20 B1=SUM[31] 
+ B2=M_result[21] 
Xi_0_0_406 INV_X1 $PINS ZN=n_0_0_319 A=n_0_0_320 
Xi_0_0_405 OAI22_X1 $PINS ZN=n_0_0_318 A1=n_0_0_519 A2=n_0_19 B1=SUM[31] 
+ B2=M_result[20] 
Xi_0_0_404 NAND2_X1 $PINS ZN=n_0_0_317 A1=n_0_0_320 A2=n_0_0_318 
Xi_0_0_403 NAND3_X1 $PINS ZN=n_0_0_316 A1=n_0_0_320 A2=n_0_0_318 A3=n_0_0_321 
Xi_0_0_402 OAI22_X1 $PINS ZN=n_0_0_315 A1=n_0_0_519 A2=n_0_18 B1=SUM[31] 
+ B2=M_result[19] 
Xi_0_0_401 OAI22_X1 $PINS ZN=n_0_0_314 A1=n_0_0_519 A2=n_0_17 B1=SUM[31] 
+ B2=M_result[18] 
Xi_0_0_400 INV_X1 $PINS ZN=n_0_0_313 A=n_0_0_314 
Xi_0_0_399 NAND2_X1 $PINS ZN=n_0_0_312 A1=n_0_0_315 A2=n_0_0_314 
Xi_0_0_398 OAI22_X1 $PINS ZN=n_0_0_311 A1=n_0_0_519 A2=n_0_16 B1=SUM[31] 
+ B2=M_result[17] 
Xi_0_0_397 OAI22_X1 $PINS ZN=n_0_0_310 A1=n_0_0_519 A2=n_0_15 B1=SUM[31] 
+ B2=M_result[16] 
Xi_0_0_396 NAND2_X1 $PINS ZN=n_0_0_309 A1=n_0_0_311 A2=n_0_0_310 
Xi_0_0_395 NOR2_X1 $PINS ZN=n_0_0_308 A1=n_0_0_312 A2=n_0_0_309 
Xi_0_0_394 NAND4_X1 $PINS ZN=n_0_0_307 A1=n_0_0_320 A2=n_0_0_318 A3=n_0_0_321 
+ A4=n_0_0_308 
Xi_0_0_393 NOR2_X1 $PINS ZN=n_0_0_306 A1=n_0_0_325 A2=n_0_0_307 
Xi_0_0_392 OAI22_X1 $PINS ZN=n_0_0_305 A1=n_0_0_519 A2=n_0_14 B1=SUM[31] 
+ B2=M_result[15] 
Xi_0_0_391 INV_X1 $PINS ZN=n_0_0_304 A=n_0_0_305 
Xi_0_0_390 OAI22_X1 $PINS ZN=n_0_0_303 A1=n_0_0_519 A2=n_0_13 B1=SUM[31] 
+ B2=M_result[14] 
Xi_0_0_389 INV_X1 $PINS ZN=n_0_0_302 A=n_0_0_303 
Xi_0_0_388 OAI22_X1 $PINS ZN=n_0_0_301 A1=n_0_0_519 A2=n_0_12 B1=SUM[31] 
+ B2=M_result[13] 
Xi_0_0_387 INV_X1 $PINS ZN=n_0_0_300 A=n_0_0_301 
Xi_0_0_386 OAI22_X1 $PINS ZN=n_0_0_299 A1=n_0_0_519 A2=n_0_11 B1=SUM[31] 
+ B2=M_result[12] 
Xi_0_0_385 INV_X1 $PINS ZN=n_0_0_298 A=n_0_0_299 
Xi_0_0_384 NOR2_X1 $PINS ZN=n_0_0_297 A1=n_0_0_300 A2=n_0_0_298 
Xi_0_0_383 NAND3_X1 $PINS ZN=n_0_0_296 A1=n_0_0_305 A2=n_0_0_303 A3=n_0_0_297 
Xi_0_0_382 OAI22_X1 $PINS ZN=n_0_0_295 A1=n_0_0_519 A2=n_0_10 B1=SUM[31] 
+ B2=M_result[11] 
Xi_0_0_381 INV_X1 $PINS ZN=n_0_0_294 A=n_0_0_295 
Xi_0_0_380 OAI22_X1 $PINS ZN=n_0_0_293 A1=n_0_0_519 A2=n_0_9 B1=SUM[31] 
+ B2=M_result[10] 
Xi_0_0_379 INV_X1 $PINS ZN=n_0_0_292 A=n_0_0_293 
Xi_0_0_378 NOR2_X1 $PINS ZN=n_0_0_291 A1=n_0_0_294 A2=n_0_0_292 
Xi_0_0_377 AOI22_X1 $PINS ZN=n_0_0_290 A1=n_0_0_519 A2=M_result[9] B1=SUM[31] 
+ B2=n_0_8 
Xi_0_0_376 INV_X1 $PINS ZN=n_0_0_289 A=n_0_0_290 
Xi_0_0_375 OAI22_X1 $PINS ZN=n_0_0_288 A1=n_0_0_519 A2=n_0_7 B1=SUM[31] 
+ B2=M_result[8] 
Xi_0_0_374 NAND2_X1 $PINS ZN=n_0_0_287 A1=n_0_0_290 A2=n_0_0_288 
Xi_0_0_373 NAND3_X1 $PINS ZN=n_0_0_286 A1=n_0_0_290 A2=n_0_0_288 A3=n_0_0_291 
Xi_0_0_372 NOR2_X1 $PINS ZN=n_0_0_285 A1=n_0_0_296 A2=n_0_0_286 
Xi_0_0_371 OAI22_X1 $PINS ZN=n_0_0_284 A1=n_0_0_519 A2=n_0_4 B1=SUM[31] 
+ B2=M_result[5] 
Xi_0_0_370 INV_X1 $PINS ZN=n_0_0_283 A=n_0_0_284 
Xi_0_0_369 OAI22_X1 $PINS ZN=n_0_0_282 A1=n_0_0_519 A2=n_0_3 B1=SUM[31] 
+ B2=M_result[4] 
Xi_0_0_368 INV_X1 $PINS ZN=n_0_0_281 A=n_0_0_282 
Xi_0_0_367 NOR2_X1 $PINS ZN=n_0_0_280 A1=n_0_0_283 A2=n_0_0_281 
Xi_0_0_366 INV_X1 $PINS ZN=n_0_0_279 A=n_0_0_280 
Xi_0_0_365 AOI22_X1 $PINS ZN=n_0_0_278 A1=n_0_0_519 A2=M_result[3] B1=SUM[31] 
+ B2=n_0_2 
Xi_0_0_364 INV_X1 $PINS ZN=n_0_0_277 A=n_0_0_278 
Xi_0_0_363 AOI22_X1 $PINS ZN=n_0_0_276 A1=n_0_0_519 A2=M_result[2] B1=SUM[31] 
+ B2=n_0_1 
Xi_0_0_362 INV_X1 $PINS ZN=n_0_0_275 A=n_0_0_276 
Xi_0_0_361 AOI21_X1 $PINS ZN=n_0_0_274 A=n_0_0_279 B1=n_0_0_278 B2=n_0_0_276 
Xi_0_0_360 OAI22_X1 $PINS ZN=n_0_0_273 A1=n_0_0_519 A2=n_0_6 B1=SUM[31] 
+ B2=M_result[7] 
Xi_0_0_359 INV_X1 $PINS ZN=n_0_0_272 A=n_0_0_273 
Xi_0_0_358 OAI22_X1 $PINS ZN=n_0_0_271 A1=n_0_0_519 A2=n_0_5 B1=SUM[31] 
+ B2=M_result[6] 
Xi_0_0_357 INV_X1 $PINS ZN=n_0_0_270 A=n_0_0_271 
Xi_0_0_356 NOR2_X1 $PINS ZN=n_0_0_269 A1=n_0_0_272 A2=n_0_0_270 
Xi_0_0_355 NOR3_X1 $PINS ZN=n_0_0_268 A1=n_0_0_272 A2=n_0_0_270 A3=n_0_0_274 
Xi_0_0_354 AOI22_X1 $PINS ZN=n_0_0_267 A1=n_0_0_519 A2=M_result[1] B1=SUM[31] 
+ B2=n_0_0 
Xi_0_0_353 INV_X1 $PINS ZN=n_0_0_266 A=n_0_0_267 
Xi_0_0_352 NOR3_X1 $PINS ZN=n_0_0_265 A1=M_result[0] A2=n_0_0_266 A3=n_0_0_279 
Xi_0_0_351 NAND4_X1 $PINS ZN=n_0_0_264 A1=n_0_0_268 A2=n_0_0_265 A3=n_0_0_285 
+ A4=n_0_0_306 
Xi_0_0_350 INV_X1 $PINS ZN=n_0_0_263 A=n_0_0_264 
Xi_0_0_349 OAI21_X1 $PINS ZN=n_0_0_262 A=n_0_0_329 B1=n_0_0_519 B2=n_0_0_327 
Xi_0_0_348 INV_X1 $PINS ZN=n_0_0_261 A=n_0_0_262 
Xi_0_0_347 AOI21_X1 $PINS ZN=n_0_0_260 A=n_0_0_277 B1=n_0_0_276 B2=n_0_0_266 
Xi_0_0_346 OAI21_X1 $PINS ZN=n_0_0_259 A=n_0_0_284 B1=n_0_0_281 B2=n_0_0_260 
Xi_0_0_345 INV_X1 $PINS ZN=n_0_0_258 A=n_0_0_259 
Xi_0_0_344 OAI21_X1 $PINS ZN=n_0_0_257 A=n_0_0_273 B1=n_0_0_270 B2=n_0_0_258 
Xi_0_0_343 AOI21_X1 $PINS ZN=n_0_0_256 A=n_0_0_289 B1=n_0_0_288 B2=n_0_0_257 
Xi_0_0_342 OAI21_X1 $PINS ZN=n_0_0_255 A=n_0_0_295 B1=n_0_0_292 B2=n_0_0_256 
Xi_0_0_341 AOI21_X1 $PINS ZN=n_0_0_254 A=n_0_0_300 B1=n_0_0_299 B2=n_0_0_255 
Xi_0_0_340 OAI21_X1 $PINS ZN=n_0_0_253 A=n_0_0_305 B1=n_0_0_302 B2=n_0_0_254 
Xi_0_0_339 AND4_X1 $PINS ZN=n_0_0_252 A1=n_0_0_323 A2=n_0_0_318 A3=n_0_0_314 
+ A4=n_0_0_310 
Xi_0_0_338 OAI21_X1 $PINS ZN=n_0_0_251 A=n_0_0_315 B1=n_0_0_313 B2=n_0_0_311 
Xi_0_0_337 AOI21_X1 $PINS ZN=n_0_0_250 A=n_0_0_319 B1=n_0_0_318 B2=n_0_0_251 
Xi_0_0_336 OAI21_X1 $PINS ZN=n_0_0_249 A=n_0_0_324 B1=n_0_0_322 B2=n_0_0_250 
Xi_0_0_335 AOI21_X1 $PINS ZN=n_0_0_248 A=n_0_0_249 B1=n_0_0_253 B2=n_0_0_252 
Xi_0_0_334 OAI21_X1 $PINS ZN=n_0_0_247 A=SUM[31] B1=n_0_25 B2=n_0_24 
Xi_0_0_333 OAI21_X1 $PINS ZN=n_0_0_246 A=n_0_0_247 B1=n_0_0_261 B2=n_0_0_248 
Xi_0_0_332 OAI21_X1 $PINS ZN=n_0_0_245 A=n_0_0_264 B1=n_0_0_519 B2=n_0_0_518 
Xi_0_0_331 OAI21_X1 $PINS ZN=n_0_0_244 A=n_0_0_291 B1=n_0_0_287 B2=n_0_0_268 
Xi_0_0_330 AOI211_X1 $PINS ZN=n_0_0_243 A=n_0_0_304 B=n_0_0_302 C1=n_0_0_297 
+ C2=n_0_0_244 
Xi_0_0_329 NOR2_X1 $PINS ZN=n_0_0_242 A1=n_0_0_309 A2=n_0_0_243 
Xi_0_0_328 NOR2_X1 $PINS ZN=n_0_0_241 A1=n_0_0_312 A2=n_0_0_242 
Xi_0_0_327 OAI21_X1 $PINS ZN=n_0_0_240 A=n_0_0_321 B1=n_0_0_317 B2=n_0_0_241 
Xi_0_0_326 OAI21_X1 $PINS ZN=n_0_0_239 A=n_0_0_329 B1=n_0_23 B2=n_0_0_328 
Xi_0_0_325 AOI21_X1 $PINS ZN=n_0_0_238 A=n_0_0_245 B1=n_0_0_240 B2=n_0_0_239 
Xi_0_0_324 INV_X1 $PINS ZN=n_0_0_237 A=n_0_0_238 
Xi_0_0_323 OR2_X1 $PINS ZN=n_0_0_236 A1=n_0_0_246 A2=n_0_0_237 
Xi_0_0_322 AOI21_X1 $PINS ZN=n_0_0_235 A=n_0_0_286 B1=n_0_0_280 B2=n_0_0_269 
Xi_0_0_321 OAI21_X1 $PINS ZN=n_0_0_234 A=n_0_0_308 B1=n_0_0_296 B2=n_0_0_235 
Xi_0_0_320 INV_X1 $PINS ZN=n_0_0_233 A=n_0_0_234 
Xi_0_0_319 OAI21_X1 $PINS ZN=n_0_0_232 A=n_0_0_326 B1=n_0_0_316 B2=n_0_0_233 
Xi_0_0_318 INV_X1 $PINS ZN=n_0_0_231 A=n_0_0_232 
Xi_0_0_317 NOR2_X1 $PINS ZN=n_0_0_230 A1=n_0_0_236 A2=n_0_0_231 
Xi_0_0_316 NAND2_X1 $PINS ZN=n_0_0_229 A1=n_0_0_325 A2=n_0_0_230 
Xi_0_0_315 INV_X1 $PINS ZN=n_0_0_228 A=n_0_0_229 
Xi_0_0_314 NOR2_X1 $PINS ZN=n_0_0_227 A1=n_0_0_263 A2=n_0_0_228 
Xi_0_0_313 INV_X1 $PINS ZN=n_0_0_226 A=n_0_0_227 
Xi_0_0_312 XNOR2_X1 $PINS ZN=n_0_0_225 A=n_0_0_13 B=n_0_125 
Xi_0_0_311 XNOR2_X1 $PINS ZN=n_0_0_224 A=n_0_126 B=n_0_0_225 
Xi_0_0_310 XNOR2_X1 $PINS ZN=n_0_0_223 A=n_0_0_7 B=n_0_126 
Xi_0_0_309 OAI22_X1 $PINS ZN=n_0_0_222 A1=n_0_0_226 A2=n_0_0_224 B1=n_0_0_229 
+ B2=n_0_0_223 
Xi_0_0_308 INV_X1 $PINS ZN=n_0_0_221 A=n_0_0_222 
Xi_0_0_307 NAND4_X1 $PINS ZN=n_0_0_220 A1=A[26] A2=A[25] A3=A[24] A4=A[23] 
Xi_0_0_306 NAND4_X1 $PINS ZN=n_0_0_219 A1=A[30] A2=A[29] A3=A[28] A4=A[27] 
Xi_0_0_305 NAND4_X1 $PINS ZN=n_0_0_218 A1=B[26] A2=B[25] A3=B[24] A4=B[23] 
Xi_0_0_304 NAND4_X1 $PINS ZN=n_0_0_217 A1=B[30] A2=B[29] A3=B[28] A4=B[27] 
Xi_0_0_303 OAI22_X1 $PINS ZN=n_0_0_216 A1=n_0_0_220 A2=n_0_0_219 B1=n_0_0_218 
+ B2=n_0_0_217 
Xi_0_0_302 INV_X1 $PINS ZN=n_0_0_215 A=n_0_0_216 
Xi_0_0_301 NAND2_X1 $PINS ZN=SUM[30] A1=n_0_0_221 A2=n_0_0_215 
Xi_0_0_300 AOI22_X1 $PINS ZN=n_0_0_214 A1=n_0_0_24 A2=n_0_0_227 B1=n_0_0_30 
+ B2=n_0_0_228 
Xi_0_0_299 NAND2_X1 $PINS ZN=SUM[29] A1=n_0_0_215 A2=n_0_0_214 
Xi_0_0_298 AOI22_X1 $PINS ZN=n_0_0_213 A1=n_0_0_23 A2=n_0_0_227 B1=n_0_0_29 
+ B2=n_0_0_228 
Xi_0_0_297 NAND2_X1 $PINS ZN=SUM[28] A1=n_0_0_215 A2=n_0_0_213 
Xi_0_0_296 AOI22_X1 $PINS ZN=n_0_0_212 A1=n_0_0_22 A2=n_0_0_227 B1=n_0_0_28 
+ B2=n_0_0_228 
Xi_0_0_295 NAND2_X1 $PINS ZN=SUM[27] A1=n_0_0_215 A2=n_0_0_212 
Xi_0_0_294 AOI22_X1 $PINS ZN=n_0_0_211 A1=n_0_0_21 A2=n_0_0_227 B1=n_0_0_27 
+ B2=n_0_0_228 
Xi_0_0_293 NAND2_X1 $PINS ZN=SUM[26] A1=n_0_0_215 A2=n_0_0_211 
Xi_0_0_292 AOI22_X1 $PINS ZN=n_0_0_210 A1=n_0_0_20 A2=n_0_0_227 B1=n_0_0_26 
+ B2=n_0_0_228 
Xi_0_0_291 NAND2_X1 $PINS ZN=SUM[25] A1=n_0_0_215 A2=n_0_0_210 
Xi_0_0_290 AOI22_X1 $PINS ZN=n_0_0_209 A1=n_0_0_19 A2=n_0_0_227 B1=n_0_0_25 
+ B2=n_0_0_228 
Xi_0_0_289 NAND2_X1 $PINS ZN=SUM[24] A1=n_0_0_215 A2=n_0_0_209 
Xi_0_0_288 NOR2_X2 $PINS ZN=n_0_0_208 A1=n_0_0_263 A2=n_0_0_246 
Xi_0_0_287 INV_X1 $PINS ZN=n_0_0_207 A=n_0_0_208 
Xi_0_0_286 NAND2_X1 $PINS ZN=n_0_0_17 A1=n_0_0_485 A2=n_0_0_208 
Xi_0_0_285 AOI22_X1 $PINS ZN=n_0_0_206 A1=n_0_0_485 A2=n_0_0_208 B1=n_0_119 
+ B2=n_0_0_246 
Xi_0_0_284 NAND2_X1 $PINS ZN=SUM[23] A1=n_0_0_215 A2=n_0_0_206 
Xi_0_0_283 OR4_X1 $PINS ZN=n_0_0_205 A1=n_0_0_212 A2=n_0_0_211 A3=n_0_0_210 
+ A4=n_0_0_209 
Xi_0_0_282 OR4_X1 $PINS ZN=n_0_0_204 A1=n_0_0_221 A2=n_0_0_206 A3=n_0_0_214 
+ A4=n_0_0_213 
Xi_0_0_281 NOR2_X1 $PINS ZN=n_0_0_203 A1=n_0_0_205 A2=n_0_0_204 
Xi_0_0_280 OR2_X1 $PINS ZN=n_0_0_202 A1=n_0_0_216 A2=n_0_0_203 
Xi_0_0_279 OR2_X1 $PINS ZN=n_0_0_201 A1=n_0_0_229 A2=n_0_0_202 
Xi_0_0_278 OAI21_X1 $PINS ZN=n_0_0_200 A=n_0_0_236 B1=n_0_0_238 B2=n_0_0_208 
Xi_0_0_277 INV_X1 $PINS ZN=n_0_0_199 A=n_0_0_200 
Xi_0_0_276 OR2_X1 $PINS ZN=n_0_0_198 A1=n_0_0_245 A2=n_0_0_231 
Xi_0_0_275 AOI21_X2 $PINS ZN=n_0_0_197 A=n_0_0_230 B1=n_0_0_236 B2=n_0_0_198 
Xi_0_0_274 INV_X1 $PINS ZN=n_0_0_196 A=n_0_0_197 
Xi_0_0_273 NOR2_X1 $PINS ZN=n_0_0_195 A1=n_0_0_325 A2=n_0_0_263 
Xi_0_0_272 OAI21_X1 $PINS ZN=n_0_0_194 A=n_0_0_195 B1=n_0_0_307 B2=n_0_0_285 
Xi_0_0_271 INV_X1 $PINS ZN=n_0_0_16 A=n_0_0_194 
Xi_0_0_270 NOR2_X1 $PINS ZN=n_0_0_193 A1=n_0_0_230 A2=n_0_0_16 
Xi_0_0_269 NAND2_X1 $PINS ZN=n_0_0_192 A1=n_0_0_306 A2=n_0_0_264 
Xi_0_0_268 OAI22_X1 $PINS ZN=n_0_0_191 A1=n_0_0_193 A2=n_0_0_192 B1=n_0_0_230 
+ B2=n_0_0_195 
Xi_0_0_267 INV_X1 $PINS ZN=n_0_0_190 A=n_0_0_191 
Xi_0_0_266 AOI21_X2 $PINS ZN=n_0_0_189 A=n_0_0_193 B1=n_0_0_230 B2=n_0_0_16 
Xi_0_0_265 INV_X1 $PINS ZN=n_0_0_188 A=n_0_0_189 
Xi_0_0_264 OAI21_X1 $PINS ZN=n_0_0_187 A=n_0_0_318 B1=n_0_0_299 B2=n_0_0_189 
Xi_0_0_263 INV_X1 $PINS ZN=n_0_0_186 A=n_0_0_187 
Xi_0_0_262 OR2_X1 $PINS ZN=n_0_0_185 A1=n_0_0_192 A2=n_0_0_188 
Xi_0_0_261 OAI22_X1 $PINS ZN=n_0_0_184 A1=n_0_0_191 A2=n_0_0_186 B1=n_0_0_282 
+ B2=n_0_0_185 
Xi_0_0_260 NAND2_X1 $PINS ZN=n_0_0_183 A1=n_0_0_190 A2=n_0_0_188 
Xi_0_0_259 OAI22_X1 $PINS ZN=n_0_0_182 A1=n_0_0_288 A2=n_0_0_183 B1=n_0_0_310 
+ B2=n_0_0_188 
Xi_0_0_258 AOI22_X1 $PINS ZN=n_0_0_181 A1=n_0_0_196 A2=n_0_0_184 B1=n_0_0_197 
+ B2=n_0_0_182 
Xi_0_0_257 NAND2_X1 $PINS ZN=n_0_0_180 A1=n_0_0_192 A2=n_0_0_189 
Xi_0_0_256 OAI222_X1 $PINS ZN=n_0_0_179 A1=n_0_0_314 A2=n_0_0_180 B1=n_0_0_276 
+ B2=n_0_0_185 C1=n_0_0_293 C2=n_0_0_183 
Xi_0_0_255 AOI21_X1 $PINS ZN=n_0_0_178 A=n_0_0_322 B1=n_0_0_302 B2=n_0_0_188 
Xi_0_0_254 OAI221_X1 $PINS ZN=n_0_0_177 A=n_0_0_200 B1=n_0_0_271 B2=n_0_0_185 
+ C1=n_0_0_191 C2=n_0_0_178 
Xi_0_0_253 AOI21_X1 $PINS ZN=n_0_0_176 A=n_0_0_177 B1=n_0_0_197 B2=n_0_0_179 
Xi_0_0_252 AOI21_X1 $PINS ZN=n_0_0_175 A=n_0_0_176 B1=n_0_0_199 B2=n_0_0_181 
Xi_0_0_251 NOR2_X2 $PINS ZN=n_0_0_174 A1=n_0_0_228 A2=n_0_0_202 
Xi_0_0_250 INV_X1 $PINS ZN=n_0_0_173 A=n_0_0_174 
Xi_0_0_249 OAI222_X1 $PINS ZN=n_0_0_172 A1=n_0_0_311 A2=n_0_0_180 B1=n_0_0_267 
+ B2=n_0_0_185 C1=n_0_0_290 C2=n_0_0_183 
Xi_0_0_248 AOI21_X1 $PINS ZN=n_0_0_171 A=n_0_0_319 B1=n_0_0_300 B2=n_0_0_188 
Xi_0_0_247 OAI22_X1 $PINS ZN=n_0_0_170 A1=n_0_0_284 A2=n_0_0_185 B1=n_0_0_191 
+ B2=n_0_0_171 
Xi_0_0_246 AOI21_X1 $PINS ZN=n_0_0_169 A=n_0_0_170 B1=n_0_0_197 B2=n_0_0_172 
Xi_0_0_245 OAI222_X1 $PINS ZN=n_0_0_168 A1=n_0_0_315 A2=n_0_0_180 B1=n_0_0_278 
+ B2=n_0_0_185 C1=n_0_0_295 C2=n_0_0_183 
Xi_0_0_244 INV_X1 $PINS ZN=n_0_0_167 A=n_0_0_168 
Xi_0_0_243 OAI21_X1 $PINS ZN=n_0_0_166 A=n_0_0_324 B1=n_0_0_305 B2=n_0_0_189 
Xi_0_0_242 OAI21_X1 $PINS ZN=n_0_0_165 A=n_0_0_208 B1=n_0_0_273 B2=n_0_0_185 
Xi_0_0_241 AOI21_X1 $PINS ZN=n_0_0_164 A=n_0_0_165 B1=n_0_0_190 B2=n_0_0_166 
Xi_0_0_240 OAI221_X1 $PINS ZN=n_0_0_163 A=n_0_0_164 B1=n_0_0_196 B2=n_0_0_167 
+ C1=n_0_0_200 C2=n_0_0_169 
Xi_0_0_239 OAI211_X1 $PINS ZN=n_0_0_162 A=n_0_0_174 B=n_0_0_163 C1=n_0_0_208 
+ C2=n_0_0_175 
Xi_0_0_238 OAI21_X1 $PINS ZN=SUM[22] A=n_0_0_162 B1=n_0_0_324 B2=n_0_0_201 
Xi_0_0_237 NAND2_X1 $PINS ZN=n_0_0_161 A1=n_0_0_197 A2=n_0_0_190 
Xi_0_0_236 OAI22_X1 $PINS ZN=n_0_0_160 A1=n_0_0_272 A2=n_0_0_189 B1=n_0_0_304 
+ B2=n_0_0_188 
Xi_0_0_235 NOR2_X1 $PINS ZN=n_0_0_159 A1=n_0_0_161 A2=n_0_0_160 
Xi_0_0_234 AOI21_X1 $PINS ZN=n_0_0_158 A=n_0_0_159 B1=n_0_0_196 B2=n_0_0_168 
Xi_0_0_233 OAI22_X1 $PINS ZN=n_0_0_157 A1=n_0_0_199 A2=n_0_0_169 B1=n_0_0_200 
+ B2=n_0_0_158 
Xi_0_0_232 OAI221_X1 $PINS ZN=n_0_0_156 A=n_0_0_174 B1=n_0_0_208 B2=n_0_0_157 
+ C1=n_0_0_207 C2=n_0_0_175 
Xi_0_0_231 OAI21_X1 $PINS ZN=SUM[21] A=n_0_0_156 B1=n_0_0_323 B2=n_0_0_201 
Xi_0_0_230 OAI22_X1 $PINS ZN=n_0_0_155 A1=n_0_0_270 A2=n_0_0_189 B1=n_0_0_302 
+ B2=n_0_0_188 
Xi_0_0_229 NOR2_X1 $PINS ZN=n_0_0_154 A1=n_0_0_161 A2=n_0_0_155 
Xi_0_0_228 AOI21_X1 $PINS ZN=n_0_0_153 A=n_0_0_154 B1=n_0_0_196 B2=n_0_0_179 
Xi_0_0_227 OAI22_X1 $PINS ZN=n_0_0_152 A1=n_0_0_200 A2=n_0_0_153 B1=n_0_0_199 
+ B2=n_0_0_181 
Xi_0_0_226 OAI221_X1 $PINS ZN=n_0_0_151 A=n_0_0_174 B1=n_0_0_207 B2=n_0_0_157 
+ C1=n_0_0_208 C2=n_0_0_152 
Xi_0_0_225 OAI21_X1 $PINS ZN=SUM[20] A=n_0_0_151 B1=n_0_0_320 B2=n_0_0_201 
Xi_0_0_224 OAI22_X1 $PINS ZN=n_0_0_150 A1=n_0_0_283 A2=n_0_0_189 B1=n_0_0_300 
+ B2=n_0_0_188 
Xi_0_0_223 NOR2_X1 $PINS ZN=n_0_0_149 A1=n_0_0_161 A2=n_0_0_150 
Xi_0_0_222 AOI21_X1 $PINS ZN=n_0_0_148 A=n_0_0_149 B1=n_0_0_196 B2=n_0_0_172 
Xi_0_0_221 OAI22_X1 $PINS ZN=n_0_0_147 A1=n_0_0_200 A2=n_0_0_148 B1=n_0_0_199 
+ B2=n_0_0_158 
Xi_0_0_220 OAI221_X1 $PINS ZN=n_0_0_146 A=n_0_0_174 B1=n_0_0_207 B2=n_0_0_152 
+ C1=n_0_0_208 C2=n_0_0_147 
Xi_0_0_219 OAI21_X1 $PINS ZN=SUM[19] A=n_0_0_146 B1=n_0_0_318 B2=n_0_0_201 
Xi_0_0_218 OAI22_X1 $PINS ZN=n_0_0_145 A1=n_0_0_281 A2=n_0_0_189 B1=n_0_0_298 
+ B2=n_0_0_188 
Xi_0_0_217 NOR2_X1 $PINS ZN=n_0_0_144 A1=n_0_0_161 A2=n_0_0_145 
Xi_0_0_216 AOI21_X1 $PINS ZN=n_0_0_143 A=n_0_0_144 B1=n_0_0_196 B2=n_0_0_182 
Xi_0_0_215 OAI22_X1 $PINS ZN=n_0_0_142 A1=n_0_0_200 A2=n_0_0_143 B1=n_0_0_199 
+ B2=n_0_0_153 
Xi_0_0_214 OAI221_X1 $PINS ZN=n_0_0_141 A=n_0_0_174 B1=n_0_0_208 B2=n_0_0_142 
+ C1=n_0_0_207 C2=n_0_0_147 
Xi_0_0_213 OAI21_X1 $PINS ZN=SUM[18] A=n_0_0_141 B1=n_0_0_315 B2=n_0_0_201 
Xi_0_0_212 NAND2_X1 $PINS ZN=n_0_0_140 A1=n_0_0_196 A2=n_0_0_190 
Xi_0_0_211 OAI22_X1 $PINS ZN=n_0_0_139 A1=n_0_0_277 A2=n_0_0_189 B1=n_0_0_294 
+ B2=n_0_0_188 
Xi_0_0_210 OAI22_X1 $PINS ZN=n_0_0_138 A1=n_0_0_160 A2=n_0_0_140 B1=n_0_0_161 
+ B2=n_0_0_139 
Xi_0_0_209 INV_X1 $PINS ZN=n_0_0_137 A=n_0_0_138 
Xi_0_0_208 AOI22_X1 $PINS ZN=n_0_0_136 A1=n_0_0_200 A2=n_0_0_148 B1=n_0_0_199 
+ B2=n_0_0_137 
Xi_0_0_207 OAI221_X1 $PINS ZN=n_0_0_135 A=n_0_0_174 B1=n_0_0_207 B2=n_0_0_142 
+ C1=n_0_0_208 C2=n_0_0_136 
Xi_0_0_206 OAI21_X1 $PINS ZN=SUM[17] A=n_0_0_135 B1=n_0_0_314 B2=n_0_0_201 
Xi_0_0_205 OAI22_X1 $PINS ZN=n_0_0_134 A1=n_0_0_275 A2=n_0_0_189 B1=n_0_0_292 
+ B2=n_0_0_188 
Xi_0_0_204 OAI22_X1 $PINS ZN=n_0_0_133 A1=n_0_0_155 A2=n_0_0_140 B1=n_0_0_161 
+ B2=n_0_0_134 
Xi_0_0_203 INV_X1 $PINS ZN=n_0_0_132 A=n_0_0_133 
Xi_0_0_202 OAI22_X1 $PINS ZN=n_0_0_131 A1=n_0_0_200 A2=n_0_0_132 B1=n_0_0_199 
+ B2=n_0_0_143 
Xi_0_0_201 OAI221_X1 $PINS ZN=n_0_0_130 A=n_0_0_174 B1=n_0_0_208 B2=n_0_0_131 
+ C1=n_0_0_207 C2=n_0_0_136 
Xi_0_0_200 OAI21_X1 $PINS ZN=SUM[16] A=n_0_0_130 B1=n_0_0_311 B2=n_0_0_201 
Xi_0_0_199 OAI22_X1 $PINS ZN=n_0_0_129 A1=n_0_0_266 A2=n_0_0_189 B1=n_0_0_289 
+ B2=n_0_0_188 
Xi_0_0_198 OAI22_X1 $PINS ZN=n_0_0_128 A1=n_0_0_150 A2=n_0_0_140 B1=n_0_0_161 
+ B2=n_0_0_129 
Xi_0_0_197 INV_X1 $PINS ZN=n_0_0_127 A=n_0_0_128 
Xi_0_0_196 OAI22_X1 $PINS ZN=n_0_0_126 A1=n_0_0_200 A2=n_0_0_127 B1=n_0_0_199 
+ B2=n_0_0_137 
Xi_0_0_195 OAI221_X1 $PINS ZN=n_0_0_125 A=n_0_0_174 B1=n_0_0_208 B2=n_0_0_126 
+ C1=n_0_0_207 C2=n_0_0_131 
Xi_0_0_194 OAI21_X1 $PINS ZN=SUM[15] A=n_0_0_125 B1=n_0_0_310 B2=n_0_0_201 
Xi_0_0_193 NAND2_X1 $PINS ZN=n_0_0_124 A1=n_0_0_199 A2=n_0_0_190 
Xi_0_0_192 NAND2_X1 $PINS ZN=n_0_0_123 A1=n_0_0_197 A2=n_0_0_16 
Xi_0_0_191 OAI22_X1 $PINS ZN=n_0_0_122 A1=n_0_0_197 A2=n_0_0_145 B1=n_0_0_288 
+ B2=n_0_0_123 
Xi_0_0_190 INV_X1 $PINS ZN=n_0_0_121 A=n_0_0_122 
Xi_0_0_189 OAI22_X1 $PINS ZN=n_0_0_120 A1=n_0_0_199 A2=n_0_0_132 B1=n_0_0_124 
+ B2=n_0_0_121 
Xi_0_0_188 OAI221_X1 $PINS ZN=n_0_0_119 A=n_0_0_174 B1=n_0_0_207 B2=n_0_0_126 
+ C1=n_0_0_208 C2=n_0_0_120 
Xi_0_0_187 OAI21_X1 $PINS ZN=SUM[14] A=n_0_0_119 B1=n_0_0_305 B2=n_0_0_201 
Xi_0_0_186 OAI22_X1 $PINS ZN=n_0_0_118 A1=n_0_0_197 A2=n_0_0_139 B1=n_0_0_273 
+ B2=n_0_0_123 
Xi_0_0_185 INV_X1 $PINS ZN=n_0_0_117 A=n_0_0_118 
Xi_0_0_184 OAI22_X1 $PINS ZN=n_0_0_116 A1=n_0_0_199 A2=n_0_0_127 B1=n_0_0_124 
+ B2=n_0_0_117 
Xi_0_0_183 OAI221_X1 $PINS ZN=n_0_0_115 A=n_0_0_174 B1=n_0_0_207 B2=n_0_0_120 
+ C1=n_0_0_208 C2=n_0_0_116 
Xi_0_0_182 OAI21_X1 $PINS ZN=SUM[13] A=n_0_0_115 B1=n_0_0_303 B2=n_0_0_201 
Xi_0_0_181 NAND2_X1 $PINS ZN=n_0_0_114 A1=n_0_0_200 A2=n_0_0_190 
Xi_0_0_180 OAI22_X1 $PINS ZN=n_0_0_113 A1=n_0_0_197 A2=n_0_0_134 B1=n_0_0_271 
+ B2=n_0_0_123 
Xi_0_0_179 INV_X1 $PINS ZN=n_0_0_112 A=n_0_0_113 
Xi_0_0_178 OAI22_X1 $PINS ZN=n_0_0_111 A1=n_0_0_121 A2=n_0_0_114 B1=n_0_0_124 
+ B2=n_0_0_112 
Xi_0_0_177 OAI221_X1 $PINS ZN=n_0_0_110 A=n_0_0_174 B1=n_0_0_208 B2=n_0_0_111 
+ C1=n_0_0_207 C2=n_0_0_116 
Xi_0_0_176 OAI21_X1 $PINS ZN=SUM[12] A=n_0_0_110 B1=n_0_0_301 B2=n_0_0_201 
Xi_0_0_175 OAI22_X1 $PINS ZN=n_0_0_109 A1=n_0_0_197 A2=n_0_0_129 B1=n_0_0_284 
+ B2=n_0_0_123 
Xi_0_0_174 INV_X1 $PINS ZN=n_0_0_108 A=n_0_0_109 
Xi_0_0_173 OAI22_X1 $PINS ZN=n_0_0_107 A1=n_0_0_117 A2=n_0_0_114 B1=n_0_0_124 
+ B2=n_0_0_108 
Xi_0_0_172 OAI221_X1 $PINS ZN=n_0_0_106 A=n_0_0_174 B1=n_0_0_207 B2=n_0_0_111 
+ C1=n_0_0_208 C2=n_0_0_107 
Xi_0_0_171 OAI21_X1 $PINS ZN=SUM[11] A=n_0_0_106 B1=n_0_0_299 B2=n_0_0_201 
Xi_0_0_170 NAND3_X1 $PINS ZN=n_0_0_105 A1=n_0_0_192 A2=n_0_0_189 A3=n_0_0_199 
Xi_0_0_169 OAI22_X1 $PINS ZN=n_0_0_104 A1=n_0_0_288 A2=n_0_0_197 B1=n_0_0_282 
+ B2=n_0_0_196 
Xi_0_0_168 INV_X1 $PINS ZN=n_0_0_103 A=n_0_0_104 
Xi_0_0_167 OAI22_X1 $PINS ZN=n_0_0_102 A1=n_0_0_114 A2=n_0_0_112 B1=n_0_0_105 
+ B2=n_0_0_103 
Xi_0_0_166 OAI221_X1 $PINS ZN=n_0_0_101 A=n_0_0_174 B1=n_0_0_207 B2=n_0_0_107 
+ C1=n_0_0_208 C2=n_0_0_102 
Xi_0_0_165 OAI21_X1 $PINS ZN=SUM[10] A=n_0_0_101 B1=n_0_0_295 B2=n_0_0_201 
Xi_0_0_164 AOI22_X1 $PINS ZN=n_0_0_100 A1=n_0_0_272 A2=n_0_0_196 B1=n_0_0_277 
+ B2=n_0_0_197 
Xi_0_0_163 OAI22_X1 $PINS ZN=n_0_0_99 A1=n_0_0_114 A2=n_0_0_108 B1=n_0_0_105 
+ B2=n_0_0_100 
Xi_0_0_162 OAI221_X1 $PINS ZN=n_0_0_98 A=n_0_0_174 B1=n_0_0_207 B2=n_0_0_102 
+ C1=n_0_0_208 C2=n_0_0_99 
Xi_0_0_161 OAI21_X1 $PINS ZN=SUM[9] A=n_0_0_98 B1=n_0_0_293 B2=n_0_0_201 
Xi_0_0_160 AOI22_X1 $PINS ZN=n_0_0_97 A1=n_0_0_270 A2=n_0_0_196 B1=n_0_0_275 
+ B2=n_0_0_197 
Xi_0_0_159 NAND3_X1 $PINS ZN=n_0_0_96 A1=n_0_0_192 A2=n_0_0_189 A3=n_0_0_200 
Xi_0_0_158 OAI22_X1 $PINS ZN=n_0_0_95 A1=n_0_0_105 A2=n_0_0_97 B1=n_0_0_103 
+ B2=n_0_0_96 
Xi_0_0_157 OAI221_X1 $PINS ZN=n_0_0_94 A=n_0_0_174 B1=n_0_0_208 B2=n_0_0_95 
+ C1=n_0_0_207 C2=n_0_0_99 
Xi_0_0_156 OAI21_X1 $PINS ZN=SUM[8] A=n_0_0_94 B1=n_0_0_290 B2=n_0_0_201 
Xi_0_0_155 AOI22_X1 $PINS ZN=n_0_0_93 A1=n_0_0_283 A2=n_0_0_196 B1=n_0_0_266 
+ B2=n_0_0_197 
Xi_0_0_154 OAI22_X1 $PINS ZN=n_0_0_92 A1=n_0_0_105 A2=n_0_0_93 B1=n_0_0_100 
+ B2=n_0_0_96 
Xi_0_0_153 OAI22_X1 $PINS ZN=n_0_0_91 A1=n_0_0_207 A2=n_0_0_95 B1=n_0_0_208 
+ B2=n_0_0_92 
Xi_0_0_152 OAI22_X1 $PINS ZN=SUM[7] A1=n_0_0_288 A2=n_0_0_201 B1=n_0_0_173 
+ B2=n_0_0_91 
Xi_0_0_151 OR2_X1 $PINS ZN=n_0_0_90 A1=n_0_0_197 A2=n_0_0_105 
Xi_0_0_150 OAI22_X1 $PINS ZN=n_0_0_89 A1=n_0_0_282 A2=n_0_0_90 B1=n_0_0_97 
+ B2=n_0_0_96 
Xi_0_0_149 OAI22_X1 $PINS ZN=n_0_0_88 A1=n_0_0_207 A2=n_0_0_92 B1=n_0_0_208 
+ B2=n_0_0_89 
Xi_0_0_148 OAI22_X1 $PINS ZN=SUM[6] A1=n_0_0_273 A2=n_0_0_201 B1=n_0_0_173 
+ B2=n_0_0_88 
Xi_0_0_147 OAI22_X1 $PINS ZN=n_0_0_87 A1=n_0_0_278 A2=n_0_0_90 B1=n_0_0_96 
+ B2=n_0_0_93 
Xi_0_0_146 OAI22_X1 $PINS ZN=n_0_0_86 A1=n_0_0_207 A2=n_0_0_89 B1=n_0_0_208 
+ B2=n_0_0_87 
Xi_0_0_145 OAI22_X1 $PINS ZN=SUM[5] A1=n_0_0_271 A2=n_0_0_201 B1=n_0_0_173 
+ B2=n_0_0_86 
Xi_0_0_144 OR2_X1 $PINS ZN=n_0_0_85 A1=n_0_0_197 A2=n_0_0_96 
Xi_0_0_143 OAI22_X1 $PINS ZN=n_0_0_84 A1=n_0_0_276 A2=n_0_0_90 B1=n_0_0_282 
+ B2=n_0_0_85 
Xi_0_0_142 OAI22_X1 $PINS ZN=n_0_0_83 A1=n_0_0_207 A2=n_0_0_87 B1=n_0_0_208 
+ B2=n_0_0_84 
Xi_0_0_141 OAI22_X1 $PINS ZN=SUM[4] A1=n_0_0_284 A2=n_0_0_201 B1=n_0_0_173 
+ B2=n_0_0_83 
Xi_0_0_140 OAI22_X1 $PINS ZN=n_0_0_82 A1=n_0_0_267 A2=n_0_0_90 B1=n_0_0_278 
+ B2=n_0_0_85 
Xi_0_0_139 OAI22_X1 $PINS ZN=n_0_0_81 A1=n_0_0_207 A2=n_0_0_84 B1=n_0_0_208 
+ B2=n_0_0_82 
Xi_0_0_138 OAI22_X1 $PINS ZN=SUM[3] A1=n_0_0_282 A2=n_0_0_201 B1=n_0_0_173 
+ B2=n_0_0_81 
Xi_0_0_137 OAI21_X1 $PINS ZN=n_0_0_80 A=n_0_0_207 B1=n_0_0_276 B2=n_0_0_85 
Xi_0_0_136 OAI21_X1 $PINS ZN=n_0_0_79 A=n_0_0_80 B1=n_0_0_207 B2=n_0_0_82 
Xi_0_0_135 OAI22_X1 $PINS ZN=SUM[2] A1=n_0_0_278 A2=n_0_0_201 B1=n_0_0_173 
+ B2=n_0_0_79 
Xi_0_0_134 AOI22_X1 $PINS ZN=n_0_0_78 A1=n_0_0_266 A2=n_0_0_207 B1=n_0_0_275 
+ B2=n_0_0_238 
Xi_0_0_133 OAI33_X1 $PINS ZN=SUM[1] A1=n_0_0_229 A2=n_0_0_202 A3=n_0_0_276 
+ B1=n_0_0_85 B2=n_0_0_78 B3=n_0_0_173 
Xi_0_0_132 AOI22_X1 $PINS ZN=n_0_0_77 A1=B[31] A2=n_0_0_535 B1=n_0_0_546 
+ B2=A[31] 
Xi_0_0_131 OAI33_X1 $PINS ZN=SUM[0] A1=n_0_0_229 A2=n_0_0_202 A3=n_0_0_267 
+ B1=n_0_0_215 B2=n_0_0_77 B3=n_0_0_203 
Xi_0_0_130 AND2_X1 $PINS ZN=M_shiftedmodified[31] A1=A[31] A2=n_0_49 
Xi_0_0_129 OAI22_X1 $PINS ZN=n_0_0_76 A1=A[31] A2=M_shitfed[23] B1=n_0_0_535 
+ B2=n_0_48 
Xi_0_0_128 INV_X1 $PINS ZN=M_shiftedmodified[23] A=n_0_0_76 
Xi_0_0_127 OAI22_X1 $PINS ZN=n_0_0_75 A1=A[31] A2=M_shitfed[22] B1=n_0_0_535 
+ B2=n_0_47 
Xi_0_0_126 INV_X1 $PINS ZN=M_shiftedmodified[22] A=n_0_0_75 
Xi_0_0_125 AOI22_X1 $PINS ZN=n_0_0_74 A1=A[31] A2=n_0_46 B1=n_0_0_535 
+ B2=M_shitfed[21] 
Xi_0_0_124 INV_X1 $PINS ZN=M_shiftedmodified[21] A=n_0_0_74 
Xi_0_0_123 OAI22_X1 $PINS ZN=M_shiftedmodified[20] A1=n_0_0_535 A2=n_0_0_517 
+ B1=A[31] B2=n_0_0_468 
Xi_0_0_122 OAI22_X1 $PINS ZN=M_shiftedmodified[19] A1=n_0_0_535 A2=n_0_0_516 
+ B1=A[31] B2=n_0_0_460 
Xi_0_0_121 OAI22_X1 $PINS ZN=n_0_0_73 A1=A[31] A2=M_shitfed[18] B1=n_0_0_535 
+ B2=n_0_43 
Xi_0_0_120 INV_X1 $PINS ZN=M_shiftedmodified[18] A=n_0_0_73 
Xi_0_0_119 OAI22_X1 $PINS ZN=M_shiftedmodified[17] A1=n_0_0_535 A2=n_0_0_515 
+ B1=A[31] B2=n_0_0_450 
Xi_0_0_118 OAI22_X1 $PINS ZN=M_shiftedmodified[16] A1=n_0_0_535 A2=n_0_0_514 
+ B1=A[31] B2=n_0_0_445 
Xi_0_0_117 OAI22_X1 $PINS ZN=M_shiftedmodified[15] A1=n_0_0_535 A2=n_0_0_513 
+ B1=A[31] B2=n_0_0_438 
Xi_0_0_116 OAI22_X1 $PINS ZN=M_shiftedmodified[14] A1=n_0_0_535 A2=n_0_0_512 
+ B1=A[31] B2=n_0_0_432 
Xi_0_0_115 OAI22_X1 $PINS ZN=M_shiftedmodified[13] A1=n_0_0_535 A2=n_0_0_511 
+ B1=A[31] B2=n_0_0_426 
Xi_0_0_114 OAI22_X1 $PINS ZN=M_shiftedmodified[12] A1=n_0_0_535 A2=n_0_0_510 
+ B1=A[31] B2=n_0_0_420 
Xi_0_0_113 OAI22_X1 $PINS ZN=M_shiftedmodified[11] A1=n_0_0_535 A2=n_0_0_509 
+ B1=A[31] B2=n_0_0_415 
Xi_0_0_112 OAI22_X1 $PINS ZN=M_shiftedmodified[10] A1=n_0_0_535 A2=n_0_0_508 
+ B1=A[31] B2=n_0_0_410 
Xi_0_0_111 OAI22_X1 $PINS ZN=M_shiftedmodified[9] A1=n_0_0_535 A2=n_0_0_507 
+ B1=A[31] B2=n_0_0_405 
Xi_0_0_110 OAI22_X1 $PINS ZN=M_shiftedmodified[8] A1=n_0_0_535 A2=n_0_0_506 
+ B1=A[31] B2=n_0_0_400 
Xi_0_0_109 OAI22_X1 $PINS ZN=M_shiftedmodified[7] A1=n_0_0_535 A2=n_0_0_505 
+ B1=A[31] B2=n_0_0_394 
Xi_0_0_108 OAI22_X1 $PINS ZN=M_shiftedmodified[6] A1=n_0_0_535 A2=n_0_0_504 
+ B1=A[31] B2=n_0_0_388 
Xi_0_0_107 OAI22_X1 $PINS ZN=M_shiftedmodified[5] A1=n_0_0_535 A2=n_0_0_503 
+ B1=A[31] B2=n_0_0_383 
Xi_0_0_106 OAI22_X1 $PINS ZN=M_shiftedmodified[4] A1=n_0_0_535 A2=n_0_0_502 
+ B1=A[31] B2=n_0_0_378 
Xi_0_0_105 OAI22_X1 $PINS ZN=M_shiftedmodified[3] A1=n_0_0_535 A2=n_0_0_501 
+ B1=A[31] B2=n_0_0_373 
Xi_0_0_104 OAI22_X1 $PINS ZN=M_shiftedmodified[2] A1=n_0_0_535 A2=n_0_0_500 
+ B1=A[31] B2=n_0_0_368 
Xi_0_0_103 OAI22_X1 $PINS ZN=M_shiftedmodified[1] A1=n_0_0_535 A2=n_0_0_499 
+ B1=A[31] B2=n_0_0_362 
Xi_0_0_102 AOI22_X1 $PINS ZN=n_0_0_72 A1=A[22] A2=n_0_0_488 B1=B[22] 
+ B2=CLOCK_sps__n1 
Xi_0_0_101 INV_X1 $PINS ZN=n_0_118 A=n_0_0_72 
Xi_0_0_100 OAI22_X1 $PINS ZN=n_0_117 A1=n_0_0_526 A2=CLOCK_sps__n1 B1=n_0_0_538 
+ B2=n_0_0_488 
Xi_0_0_99 AOI22_X1 $PINS ZN=n_0_0_71 A1=A[20] A2=n_0_0_488 B1=B[20] 
+ B2=CLOCK_sps__n1 
Xi_0_0_98 INV_X1 $PINS ZN=n_0_116 A=n_0_0_71 
Xi_0_0_97 AOI22_X1 $PINS ZN=n_0_0_70 A1=A[19] A2=n_0_0_488 B1=B[19] 
+ B2=CLOCK_sps__n1 
Xi_0_0_96 INV_X1 $PINS ZN=n_0_115 A=n_0_0_70 
Xi_0_0_95 AOI22_X1 $PINS ZN=n_0_0_69 A1=A[18] A2=n_0_0_488 B1=B[18] 
+ B2=CLOCK_sps__n1 
Xi_0_0_94 INV_X1 $PINS ZN=n_0_114 A=n_0_0_69 
Xi_0_0_93 AOI22_X1 $PINS ZN=n_0_0_68 A1=A[17] A2=n_0_0_488 B1=B[17] 
+ B2=CLOCK_sps__n1 
Xi_0_0_92 INV_X1 $PINS ZN=n_0_113 A=n_0_0_68 
Xi_0_0_91 AOI22_X1 $PINS ZN=n_0_0_67 A1=A[16] A2=n_0_0_488 B1=B[16] 
+ B2=CLOCK_sps__n1 
Xi_0_0_90 INV_X1 $PINS ZN=n_0_112 A=n_0_0_67 
Xi_0_0_89 OAI22_X1 $PINS ZN=n_0_111 A1=n_0_0_525 A2=n_0_0_487 B1=n_0_0_537 
+ B2=n_0_0_488 
Xi_0_0_88 AOI22_X1 $PINS ZN=n_0_0_66 A1=A[14] A2=n_0_0_488 B1=B[14] 
+ B2=CLOCK_sps__n1 
Xi_0_0_87 INV_X1 $PINS ZN=n_0_110 A=n_0_0_66 
Xi_0_0_86 AOI22_X1 $PINS ZN=n_0_0_65 A1=A[13] A2=n_0_0_488 B1=B[13] 
+ B2=CLOCK_sps__n1 
Xi_0_0_85 INV_X1 $PINS ZN=n_0_109 A=n_0_0_65 
Xi_0_0_84 AOI22_X1 $PINS ZN=n_0_0_64 A1=A[12] A2=n_0_0_488 B1=B[12] 
+ B2=CLOCK_sps__n1 
Xi_0_0_83 INV_X1 $PINS ZN=n_0_108 A=n_0_0_64 
Xi_0_0_82 AOI22_X1 $PINS ZN=n_0_0_63 A1=A[11] A2=n_0_0_488 B1=B[11] 
+ B2=CLOCK_sps__n1 
Xi_0_0_81 INV_X1 $PINS ZN=n_0_107 A=n_0_0_63 
Xi_0_0_80 AOI22_X1 $PINS ZN=n_0_0_62 A1=A[10] A2=n_0_0_488 B1=B[10] 
+ B2=CLOCK_sps__n1 
Xi_0_0_79 INV_X1 $PINS ZN=n_0_106 A=n_0_0_62 
Xi_0_0_78 AOI22_X1 $PINS ZN=n_0_0_61 A1=A[9] A2=n_0_0_488 B1=B[9] 
+ B2=CLOCK_sps__n1 
Xi_0_0_77 INV_X1 $PINS ZN=n_0_105 A=n_0_0_61 
Xi_0_0_76 AOI22_X1 $PINS ZN=n_0_0_60 A1=A[8] A2=n_0_0_488 B1=B[8] 
+ B2=CLOCK_sps__n1 
Xi_0_0_75 INV_X1 $PINS ZN=n_0_104 A=n_0_0_60 
Xi_0_0_74 OAI22_X1 $PINS ZN=n_0_103 A1=n_0_0_524 A2=n_0_0_487 B1=n_0_0_536 
+ B2=n_0_0_488 
Xi_0_0_73 AOI22_X1 $PINS ZN=n_0_0_59 A1=A[6] A2=n_0_0_488 B1=B[6] 
+ B2=CLOCK_sps__n1 
Xi_0_0_72 INV_X1 $PINS ZN=n_0_102 A=n_0_0_59 
Xi_0_0_71 AOI22_X1 $PINS ZN=n_0_0_58 A1=A[5] A2=n_0_0_488 B1=B[5] 
+ B2=CLOCK_sps__n1 
Xi_0_0_70 INV_X1 $PINS ZN=n_0_101 A=n_0_0_58 
Xi_0_0_69 AOI22_X1 $PINS ZN=n_0_0_57 A1=A[4] A2=n_0_0_488 B1=B[4] 
+ B2=CLOCK_sps__n1 
Xi_0_0_68 INV_X1 $PINS ZN=n_0_100 A=n_0_0_57 
Xi_0_0_67 AOI22_X1 $PINS ZN=n_0_0_56 A1=A[3] A2=n_0_0_488 B1=B[3] 
+ B2=CLOCK_sps__n1 
Xi_0_0_66 INV_X1 $PINS ZN=n_0_99 A=n_0_0_56 
Xi_0_0_65 AOI22_X1 $PINS ZN=n_0_0_55 A1=A[2] A2=n_0_0_488 B1=B[2] 
+ B2=CLOCK_sps__n1 
Xi_0_0_64 INV_X1 $PINS ZN=n_0_98 A=n_0_0_55 
Xi_0_0_63 AOI22_X1 $PINS ZN=n_0_0_54 A1=A[1] A2=n_0_0_488 B1=B[1] 
+ B2=CLOCK_sps__n1 
Xi_0_0_62 INV_X1 $PINS ZN=n_0_97 A=n_0_0_54 
Xi_0_0_61 AOI22_X1 $PINS ZN=n_0_0_53 A1=A[0] A2=n_0_0_488 B1=B[0] 
+ B2=CLOCK_sps__n1 
Xi_0_0_60 INV_X1 $PINS ZN=n_0_96 A=n_0_0_53 
Xi_0_0_59 OR2_X1 $PINS ZN=n_0_95 A1=n_0_0_546 A2=n_0_72 
Xi_0_0_58 OAI22_X1 $PINS ZN=n_0_0_52 A1=B[31] A2=n_0_118 B1=n_0_0_546 B2=n_0_71 
Xi_0_0_57 INV_X1 $PINS ZN=n_0_94 A=n_0_0_52 
Xi_0_0_56 OAI22_X1 $PINS ZN=n_0_0_51 A1=B[31] A2=n_0_117 B1=n_0_0_546 B2=n_0_70 
Xi_0_0_55 INV_X1 $PINS ZN=n_0_93 A=n_0_0_51 
Xi_0_0_54 OAI22_X1 $PINS ZN=n_0_0_50 A1=B[31] A2=n_0_116 B1=n_0_0_546 B2=n_0_69 
Xi_0_0_53 INV_X1 $PINS ZN=n_0_92 A=n_0_0_50 
Xi_0_0_52 OAI22_X1 $PINS ZN=n_0_0_49 A1=B[31] A2=n_0_115 B1=n_0_0_546 B2=n_0_68 
Xi_0_0_51 INV_X1 $PINS ZN=n_0_91 A=n_0_0_49 
Xi_0_0_50 OAI22_X1 $PINS ZN=n_0_0_48 A1=B[31] A2=n_0_114 B1=n_0_0_546 B2=n_0_67 
Xi_0_0_49 INV_X1 $PINS ZN=n_0_90 A=n_0_0_48 
Xi_0_0_48 OAI22_X1 $PINS ZN=n_0_0_47 A1=B[31] A2=n_0_113 B1=n_0_0_546 B2=n_0_66 
Xi_0_0_47 INV_X1 $PINS ZN=n_0_89 A=n_0_0_47 
Xi_0_0_46 OAI22_X1 $PINS ZN=n_0_0_46 A1=B[31] A2=n_0_112 B1=n_0_0_546 B2=n_0_65 
Xi_0_0_45 INV_X1 $PINS ZN=n_0_88 A=n_0_0_46 
Xi_0_0_44 OAI22_X1 $PINS ZN=n_0_0_45 A1=B[31] A2=n_0_111 B1=n_0_0_546 B2=n_0_64 
Xi_0_0_43 INV_X1 $PINS ZN=n_0_87 A=n_0_0_45 
Xi_0_0_42 OAI22_X1 $PINS ZN=n_0_0_44 A1=B[31] A2=n_0_110 B1=n_0_0_546 B2=n_0_63 
Xi_0_0_41 INV_X1 $PINS ZN=n_0_86 A=n_0_0_44 
Xi_0_0_40 OAI22_X1 $PINS ZN=n_0_0_43 A1=B[31] A2=n_0_109 B1=n_0_0_546 B2=n_0_62 
Xi_0_0_39 INV_X1 $PINS ZN=n_0_85 A=n_0_0_43 
Xi_0_0_38 OAI22_X1 $PINS ZN=n_0_0_42 A1=B[31] A2=n_0_108 B1=n_0_0_546 B2=n_0_61 
Xi_0_0_37 INV_X1 $PINS ZN=n_0_84 A=n_0_0_42 
Xi_0_0_36 OAI22_X1 $PINS ZN=n_0_0_41 A1=B[31] A2=n_0_107 B1=n_0_0_546 B2=n_0_60 
Xi_0_0_35 INV_X1 $PINS ZN=n_0_83 A=n_0_0_41 
Xi_0_0_34 OAI22_X1 $PINS ZN=n_0_0_40 A1=B[31] A2=n_0_106 B1=n_0_0_546 B2=n_0_59 
Xi_0_0_33 INV_X1 $PINS ZN=n_0_82 A=n_0_0_40 
Xi_0_0_32 OAI22_X1 $PINS ZN=n_0_0_39 A1=B[31] A2=n_0_105 B1=n_0_0_546 B2=n_0_58 
Xi_0_0_31 INV_X1 $PINS ZN=n_0_81 A=n_0_0_39 
Xi_0_0_30 OAI22_X1 $PINS ZN=n_0_0_38 A1=B[31] A2=n_0_104 B1=n_0_0_546 B2=n_0_57 
Xi_0_0_29 INV_X1 $PINS ZN=n_0_80 A=n_0_0_38 
Xi_0_0_28 OAI22_X1 $PINS ZN=n_0_0_37 A1=B[31] A2=n_0_103 B1=n_0_0_546 B2=n_0_56 
Xi_0_0_27 INV_X1 $PINS ZN=n_0_79 A=n_0_0_37 
Xi_0_0_26 OAI22_X1 $PINS ZN=n_0_0_36 A1=B[31] A2=n_0_102 B1=n_0_0_546 B2=n_0_55 
Xi_0_0_25 INV_X1 $PINS ZN=n_0_78 A=n_0_0_36 
Xi_0_0_24 OAI22_X1 $PINS ZN=n_0_0_35 A1=B[31] A2=n_0_101 B1=n_0_0_546 B2=n_0_54 
Xi_0_0_23 INV_X1 $PINS ZN=n_0_77 A=n_0_0_35 
Xi_0_0_22 OAI22_X1 $PINS ZN=n_0_0_34 A1=B[31] A2=n_0_100 B1=n_0_0_546 B2=n_0_53 
Xi_0_0_21 INV_X1 $PINS ZN=n_0_76 A=n_0_0_34 
Xi_0_0_20 OAI22_X1 $PINS ZN=n_0_0_33 A1=B[31] A2=n_0_99 B1=n_0_0_546 B2=n_0_52 
Xi_0_0_19 INV_X1 $PINS ZN=n_0_75 A=n_0_0_33 
Xi_0_0_18 OAI22_X1 $PINS ZN=n_0_0_32 A1=B[31] A2=n_0_98 B1=n_0_0_546 B2=n_0_51 
Xi_0_0_17 INV_X1 $PINS ZN=n_0_74 A=n_0_0_32 
Xi_0_0_16 OAI22_X1 $PINS ZN=n_0_0_31 A1=B[31] A2=n_0_97 B1=n_0_0_546 B2=n_0_50 
Xi_0_0_15 INV_X1 $PINS ZN=n_0_73 A=n_0_0_31 
Xi_0_0_14 NOR2_X1 $PINS ZN=n_0_0_15 A1=n_0_0_486 A2=n_0_0_263 
Xi_0_0_13 AOI21_X1 $PINS ZN=n_0_0_14 A=n_0_0_15 B1=n_0_0_486 B2=n_0_0_263 
Xi_0_0_12 HA_X1 $PINS CO=n_0_0_7 S=n_0_0_30 A=n_0_125 B=n_0_0_6 
Xi_0_0_11 HA_X1 $PINS CO=n_0_0_6 S=n_0_0_29 A=n_0_124 B=n_0_0_5 
Xi_0_0_10 HA_X1 $PINS CO=n_0_0_5 S=n_0_0_28 A=n_0_123 B=n_0_0_4 
Xi_0_0_9 HA_X1 $PINS CO=n_0_0_4 S=n_0_0_27 A=n_0_122 B=n_0_0_3 
Xi_0_0_8 HA_X1 $PINS CO=n_0_0_3 S=n_0_0_26 A=n_0_121 B=n_0_0_0 
Xi_0_0_7 HA_X1 $PINS CO=n_0_0_0 S=n_0_0_25 A=n_0_120 B=n_0_119 
Xi_0_0_6 FA_X1 $PINS CO=n_0_0_13 S=n_0_0_24 A=n_0_0_15 B=n_0_0_18 CI=n_0_0_12 
Xi_0_0_5 FA_X1 $PINS CO=n_0_0_12 S=n_0_0_23 A=n_0_0_2 B=n_0_0_14 CI=n_0_0_11 
Xi_0_0_4 FA_X1 $PINS CO=n_0_0_11 S=n_0_0_22 A=n_0_0_194 B=n_0_0_1 CI=n_0_0_10 
Xi_0_0_3 FA_X1 $PINS CO=n_0_0_10 S=n_0_0_21 A=n_0_122 B=n_0_0_16 CI=n_0_0_9 
Xi_0_0_2 FA_X1 $PINS CO=n_0_0_9 S=n_0_0_20 A=n_0_0_198 B=n_0_121 CI=n_0_0_8 
Xi_0_0_1 FA_X1 $PINS CO=n_0_0_8 S=n_0_0_19 A=n_0_0_237 B=n_0_120 CI=n_0_0_17 
Xi_0_0_0 HA_X1 $PINS CO=n_0_0_2 S=n_0_0_1 A=n_0_0_192 B=n_0_123 
Xi_0_19 datapath__0_24 $PINS p_0[31]=uc_40 p_0[30]=uc_41 p_0[29]=uc_42 
+ p_0[28]=uc_43 p_0[27]=uc_44 p_0[26]=uc_45 p_0[25]=uc_46 p_0[24]=uc_47 
+ p_0[23]=n_0_72 p_0[22]=n_0_71 p_0[21]=n_0_70 p_0[20]=n_0_69 p_0[19]=n_0_68 
+ p_0[18]=n_0_67 p_0[17]=n_0_66 p_0[16]=n_0_65 p_0[15]=n_0_64 p_0[14]=n_0_63 
+ p_0[13]=n_0_62 p_0[12]=n_0_61 p_0[11]=n_0_60 p_0[10]=n_0_59 p_0[9]=n_0_58 
+ p_0[8]=n_0_57 p_0[7]=n_0_56 p_0[6]=n_0_55 p_0[5]=n_0_54 p_0[4]=n_0_53 
+ p_0[3]=n_0_52 p_0[2]=n_0_51 p_0[1]=n_0_50 p_0[0]=uc_48 M_greatest[23]=VDD 
+ M_greatest[22]=n_0_118 M_greatest[21]=n_0_117 M_greatest[20]=n_0_116 
+ M_greatest[19]=n_0_115 M_greatest[18]=n_0_114 M_greatest[17]=n_0_113 
+ M_greatest[16]=n_0_112 M_greatest[15]=n_0_111 M_greatest[14]=n_0_110 
+ M_greatest[13]=n_0_109 M_greatest[12]=n_0_108 M_greatest[11]=n_0_107 
+ M_greatest[10]=n_0_106 M_greatest[9]=n_0_105 M_greatest[8]=n_0_104 
+ M_greatest[7]=n_0_103 M_greatest[6]=n_0_102 M_greatest[5]=n_0_101 
+ M_greatest[4]=n_0_100 M_greatest[3]=n_0_99 M_greatest[2]=n_0_98 
+ M_greatest[1]=n_0_97 M_greatest[0]=n_0_96 
Xi_0_16 datapath__0_21 $PINS p_0[31]=n_0_49 p_0[30]=uc_32 p_0[29]=uc_33 
+ p_0[28]=uc_34 p_0[27]=uc_35 p_0[26]=uc_36 p_0[25]=uc_37 p_0[24]=uc_38 
+ p_0[23]=n_0_48 p_0[22]=n_0_47 p_0[21]=n_0_46 p_0[20]=n_0_45 p_0[19]=n_0_44 
+ p_0[18]=n_0_43 p_0[17]=n_0_42 p_0[16]=n_0_41 p_0[15]=n_0_40 p_0[14]=n_0_39 
+ p_0[13]=n_0_38 p_0[12]=n_0_37 p_0[11]=n_0_36 p_0[10]=n_0_35 p_0[9]=n_0_34 
+ p_0[8]=n_0_33 p_0[7]=n_0_32 p_0[6]=n_0_31 p_0[5]=n_0_30 p_0[4]=n_0_29 
+ p_0[3]=n_0_28 p_0[2]=n_0_27 p_0[1]=n_0_26 p_0[0]=uc_39 
+ M_shitfed[23]=M_shitfed[23] M_shitfed[22]=M_shitfed[22] 
+ M_shitfed[21]=M_shitfed[21] M_shitfed[20]=M_shitfed[20] 
+ M_shitfed[19]=M_shitfed[19] M_shitfed[18]=M_shitfed[18] 
+ M_shitfed[17]=M_shitfed[17] M_shitfed[16]=M_shitfed[16] 
+ M_shitfed[15]=M_shitfed[15] M_shitfed[14]=M_shitfed[14] 
+ M_shitfed[13]=M_shitfed[13] M_shitfed[12]=M_shitfed[12] 
+ M_shitfed[11]=M_shitfed[11] M_shitfed[10]=M_shitfed[10] 
+ M_shitfed[9]=M_shitfed[9] M_shitfed[8]=M_shitfed[8] M_shitfed[7]=M_shitfed[7] 
+ M_shitfed[6]=M_shitfed[6] M_shitfed[5]=M_shitfed[5] M_shitfed[4]=M_shitfed[4] 
+ M_shitfed[3]=M_shitfed[3] M_shitfed[2]=M_shitfed[2] M_shitfed[1]=M_shitfed[1] 
+ M_shitfed[0]=M_shitfed[0] 
Xi_0_3 datapath__0_7 $PINS p_0[31]=uc_26 p_0[30]=uc_27 p_0[29]=uc_28 
+ p_0[28]=n_0_25 p_0[27]=uc_29 p_0[26]=uc_30 p_0[25]=n_0_24 p_0[24]=n_0_23 
+ p_0[23]=n_0_22 p_0[22]=n_0_21 p_0[21]=n_0_20 p_0[20]=n_0_19 p_0[19]=n_0_18 
+ p_0[18]=n_0_17 p_0[17]=n_0_16 p_0[16]=n_0_15 p_0[15]=n_0_14 p_0[14]=n_0_13 
+ p_0[13]=n_0_12 p_0[12]=n_0_11 p_0[11]=n_0_10 p_0[10]=n_0_9 p_0[9]=n_0_8 
+ p_0[8]=n_0_7 p_0[7]=n_0_6 p_0[6]=n_0_5 p_0[5]=n_0_4 p_0[4]=n_0_3 p_0[3]=n_0_2 
+ p_0[2]=n_0_1 p_0[1]=n_0_0 p_0[0]=uc_31 M_result[31]=uc_20 M_result[30]=uc_21 
+ M_result[29]=uc_22 M_result[28]=uc_23 M_result[27]=uc_24 M_result[26]=uc_25 
+ M_result[25]=SUM[31] M_result[24]=M_result[24] M_result[23]=M_result[23] 
+ M_result[22]=M_result[22] M_result[21]=M_result[21] M_result[20]=M_result[20] 
+ M_result[19]=M_result[19] M_result[18]=M_result[18] M_result[17]=M_result[17] 
+ M_result[16]=M_result[16] M_result[15]=M_result[15] M_result[14]=M_result[14] 
+ M_result[13]=M_result[13] M_result[12]=M_result[12] M_result[11]=M_result[11] 
+ M_result[10]=M_result[10] M_result[9]=M_result[9] M_result[8]=M_result[8] 
+ M_result[7]=M_result[7] M_result[6]=M_result[6] M_result[5]=M_result[5] 
+ M_result[4]=M_result[4] M_result[3]=M_result[3] M_result[2]=M_result[2] 
+ M_result[1]=M_result[1] M_result[0]=M_result[0] 
Xadd2 VA__parameterized0 $PINS SUM[31]=SUM[31] SUM[30]=uc_14 SUM[29]=uc_15 
+ SUM[28]=uc_16 SUM[27]=uc_17 SUM[26]=uc_18 SUM[25]=uc_19 SUM[24]=M_result[24] 
+ SUM[23]=M_result[23] SUM[22]=M_result[22] SUM[21]=M_result[21] 
+ SUM[20]=M_result[20] SUM[19]=M_result[19] SUM[18]=M_result[18] 
+ SUM[17]=M_result[17] SUM[16]=M_result[16] SUM[15]=M_result[15] 
+ SUM[14]=M_result[14] SUM[13]=M_result[13] SUM[12]=M_result[12] 
+ SUM[11]=M_result[11] SUM[10]=M_result[10] SUM[9]=M_result[9] SUM[8]=M_result[8] 
+ SUM[7]=M_result[7] SUM[6]=M_result[6] SUM[5]=M_result[5] SUM[4]=M_result[4] 
+ SUM[3]=M_result[3] SUM[2]=M_result[2] SUM[1]=M_result[1] SUM[0]=M_result[0] 
+ A[31]=M_shiftedmodified[31] A[30]=uc_0 A[29]=uc_1 A[28]=uc_2 A[27]=uc_3 
+ A[26]=uc_4 A[25]=uc_5 A[24]=uc_6 A[23]=M_shiftedmodified[23] 
+ A[22]=M_shiftedmodified[22] A[21]=M_shiftedmodified[21] 
+ A[20]=M_shiftedmodified[20] A[19]=M_shiftedmodified[19] 
+ A[18]=M_shiftedmodified[18] A[17]=M_shiftedmodified[17] 
+ A[16]=M_shiftedmodified[16] A[15]=M_shiftedmodified[15] 
+ A[14]=M_shiftedmodified[14] A[13]=M_shiftedmodified[13] 
+ A[12]=M_shiftedmodified[12] A[11]=M_shiftedmodified[11] 
+ A[10]=M_shiftedmodified[10] A[9]=M_shiftedmodified[9] A[8]=M_shiftedmodified[8] 
+ A[7]=M_shiftedmodified[7] A[6]=M_shiftedmodified[6] A[5]=M_shiftedmodified[5] 
+ A[4]=M_shiftedmodified[4] A[3]=M_shiftedmodified[3] A[2]=M_shiftedmodified[2] 
+ A[1]=M_shiftedmodified[1] A[0]=M_shitfed[0] B[31]=B[31] B[30]=uc_7 B[29]=uc_8 
+ B[28]=uc_9 B[27]=uc_10 B[26]=uc_11 B[25]=uc_12 B[24]=uc_13 B[23]=n_0_95 
+ B[22]=n_0_94 B[21]=n_0_93 B[20]=n_0_92 B[19]=n_0_91 B[18]=n_0_90 B[17]=n_0_89 
+ B[16]=n_0_88 B[15]=n_0_87 B[14]=n_0_86 B[13]=n_0_85 B[12]=n_0_84 B[11]=n_0_83 
+ B[10]=n_0_82 B[9]=n_0_81 B[8]=n_0_80 B[7]=n_0_79 B[6]=n_0_78 B[5]=n_0_77 
+ B[4]=n_0_76 B[3]=n_0_75 B[2]=n_0_74 B[1]=n_0_73 B[0]=n_0_96 
Xadd1 VA $PINS SUM[7]=E_difference[7] SUM[6]=E_difference[6] 
+ SUM[5]=E_difference[5] SUM[4]=E_difference[4] SUM[3]=E_difference[3] 
+ SUM[2]=E_difference[2] SUM[1]=E_difference[1] SUM[0]=E_difference[0] 
+ A[7]=n_0_126 A[6]=n_0_125 A[5]=n_0_124 A[4]=n_0_123 A[3]=n_0_122 A[2]=n_0_121 
+ A[1]=n_0_120 A[0]=n_0_119 B[7]=E_complement[7] B[6]=E_complement[6] 
+ B[5]=E_complement[5] B[4]=E_complement[4] B[3]=E_complement[3] 
+ B[2]=E_complement[2] B[1]=E_complement[1] B[0]=E_smallest[0] 
XCLOCK_sps__L1_c85 CLKBUF_X2 $PINS Z=CLOCK_sps__n1 A=n_0_0_487 
XCLOCK_spc__L1_c87 CLKBUF_X1 $PINS Z=CLOCK_spc__n3 A=CLOCK_spc__n5 
XCLOCK_spc__L1_c89 BUF_X1 $PINS Z=CLOCK_spc__n5 A=n_0_0_488 
.ENDS
.GLOBAL VDD 
.GLOBAL VSS 
